Repository Step3-kakao-tech-campus/Team10_BE, pull requests merged in 2023-11, with the labels that each got.

#128 refactor: awsconfig 로그 추가
  src/main/java/bdbe/bdbd/_core/errors/config/AWSConfig.java
Labels: Priority: High

#129 merge: from weekly to develop (배포)
  src/main/java/bdbe/bdbd/_core/errors/config/AWSConfig.java
Labels: Priority: High

#130 merge: from develop to main
  src/main/java/bdbe/bdbd/_core/errors/config/AWSConfig.java
Labels: Priority: High

#132 merge: from weekly to develop
  src/main/java/bdbe/bdbd/_core/errors/config/AWSConfig.java
  src/main/java/bdbe/bdbd/_core/errors/utils/FileUploadUtil.java
  src/main/java/bdbe/bdbd/carwash/CarwashService.java
Labels: Priority: High

#133 merge: from develop to main
  src/main/java/bdbe/bdbd/_core/errors/config/AWSConfig.java
  src/main/java/bdbe/bdbd/_core/errors/utils/FileUploadUtil.java
  src/main/java/bdbe/bdbd/carwash/CarwashService.java
Labels: Priority: High

#134 refactor: 파일 업로드 로그 추가
  src/main/java/bdbe/bdbd/_core/errors/utils/FileUploadUtil.java
Labels: Priority: High

#135 refactor: 사진 업로드 로깅 추가
  src/main/java/bdbe/bdbd/_core/errors/utils/FileUploadUtil.java
Labels: Priority: High

#136 refactor: 사진 업로드 로깅 추가
  src/main/java/bdbe/bdbd/_core/errors/utils/FileUploadUtil.java
Labels: Priority: High

#138 refactor: 파일 업로드시 로깅 추가
  src/main/java/bdbe/bdbd/_core/errors/utils/FileUploadUtil.java
Labels: Priority: High

#139 refactor: 파일 업로드시 로깅 추가
  src/main/java/bdbe/bdbd/_core/errors/utils/FileUploadUtil.java
Labels: Priority: High

#141 merge: from weekly to develop
  src/main/java/bdbe/bdbd/_core/errors/config/AWSConfig.java
  src/main/java/bdbe/bdbd/_core/errors/utils/FileUploadUtil.java
Labels: Priority: High

#142 merge: from develop to main
  src/main/java/bdbe/bdbd/_core/errors/config/AWSConfig.java
  src/main/java/bdbe/bdbd/_core/errors/utils/FileUploadUtil.java
Labels: Priority: High

#143 refactor: 유저, owner 회원가입 리팩토링
  src/main/java/bdbe/bdbd/_core/errors/config/AWSConfig.java
  src/main/java/bdbe/bdbd/carwash/CarwashResponse.java
  src/main/java/bdbe/bdbd/carwash/CarwashRestController.java
  src/main/java/bdbe/bdbd/file/File.java
  src/main/java/bdbe/bdbd/member/MemberRequest.java
  src/main/java/bdbe/bdbd/member/MemberRestController.java
  src/main/java/bdbe/bdbd/member/MemberService.java
  src/main/java/bdbe/bdbd/member/OwnerResponse.java
  src/main/java/bdbe/bdbd/member/OwnerRestController.java
  src/main/java/bdbe/bdbd/member/OwnerService.java
  src/main/java/bdbe/bdbd/reservation/ReservationResponse.java
  src/main/java/bdbe/bdbd/reservation/ReservationRestController.java
  src/main/java/bdbe/bdbd/reservation/ReservationService.java
  src/main/java/bdbe/bdbd/review/ReviewRequest.java
  src/main/java/bdbe/bdbd/review/ReviewService.java
  src/test/java/bdbe/bdbd/carwash/CarwashRestControllerTest.java
  src/test/java/bdbe/bdbd/member/MemberRestControllerTest.java
  src/test/java/bdbe/bdbd/member/OwnerRestControllerTest.java
  src/test/java/bdbe/bdbd/review/ReviewRestControllerTest.java
Labels: Priority: High

#144 merge: from weekly to develop
  src/main/java/bdbe/bdbd/_core/errors/config/AWSConfig.java
  src/main/java/bdbe/bdbd/carwash/CarwashResponse.java
  src/main/java/bdbe/bdbd/carwash/CarwashRestController.java
  src/main/java/bdbe/bdbd/file/File.java
  src/main/java/bdbe/bdbd/member/MemberRequest.java
  src/main/java/bdbe/bdbd/member/MemberRestController.java
  src/main/java/bdbe/bdbd/member/MemberService.java
  src/main/java/bdbe/bdbd/member/OwnerResponse.java
  src/main/java/bdbe/bdbd/member/OwnerRestController.java
  src/main/java/bdbe/bdbd/member/OwnerService.java
  src/main/java/bdbe/bdbd/reservation/ReservationResponse.java
  src/main/java/bdbe/bdbd/reservation/ReservationRestController.java
  src/main/java/bdbe/bdbd/reservation/ReservationService.java
  src/main/java/bdbe/bdbd/review/ReviewRequest.java
  src/main/java/bdbe/bdbd/review/ReviewService.java
  src/test/java/bdbe/bdbd/carwash/CarwashRestControllerTest.java
  src/test/java/bdbe/bdbd/member/MemberRestControllerTest.java
  src/test/java/bdbe/bdbd/member/OwnerRestControllerTest.java
  src/test/java/bdbe/bdbd/review/ReviewRestControllerTest.java
Labels: Priority: Urgent

#145 merge: from develop to main
  src/main/java/bdbe/bdbd/_core/errors/config/AWSConfig.java
  src/main/java/bdbe/bdbd/carwash/CarwashResponse.java
  src/main/java/bdbe/bdbd/carwash/CarwashRestController.java
  src/main/java/bdbe/bdbd/file/File.java
  src/main/java/bdbe/bdbd/member/MemberRequest.java
  src/main/java/bdbe/bdbd/member/MemberRestController.java
  src/main/java/bdbe/bdbd/member/MemberService.java
  src/main/java/bdbe/bdbd/member/OwnerResponse.java
  src/main/java/bdbe/bdbd/member/OwnerRestController.java
  src/main/java/bdbe/bdbd/member/OwnerService.java
  src/main/java/bdbe/bdbd/reservation/ReservationResponse.java
  src/main/java/bdbe/bdbd/reservation/ReservationRestController.java
  src/main/java/bdbe/bdbd/reservation/ReservationService.java
  src/main/java/bdbe/bdbd/review/ReviewRequest.java
  src/main/java/bdbe/bdbd/review/ReviewService.java
  src/test/java/bdbe/bdbd/carwash/CarwashRestControllerTest.java
  src/test/java/bdbe/bdbd/member/MemberRestControllerTest.java
  src/test/java/bdbe/bdbd/member/OwnerRestControllerTest.java
  src/test/java/bdbe/bdbd/review/ReviewRestControllerTest.java
Labels: Priority: Urgent

#147 fix: 사진 업로드 코드 수정
  src/main/java/bdbe/bdbd/_core/errors/utils/FileUploadUtil.java
  src/main/java/bdbe/bdbd/carwash/CarwashRestController.java
Labels: Priority: High

#148 fix: 사진 업로드 코드 수정
  src/main/java/bdbe/bdbd/_core/errors/utils/FileUploadUtil.java
  src/main/java/bdbe/bdbd/carwash/CarwashRestController.java
Labels: Priority: High

#149 fix: 사진 업로드 코드 수정
  src/main/java/bdbe/bdbd/_core/errors/utils/FileUploadUtil.java
  src/main/java/bdbe/bdbd/carwash/CarwashRestController.java
Labels: Priority: High

#150 fix: 세차장 등록 수정
  src/main/java/bdbe/bdbd/carwash/CarwashRestController.java
  src/main/java/bdbe/bdbd/carwash/CarwashService.java
Labels: Priority: Urgent

#151 fix: 세차장 등록 코드 수정
  src/main/java/bdbe/bdbd/carwash/CarwashRestController.java
  src/main/java/bdbe/bdbd/carwash/CarwashService.java
Labels: Priority: High

#152 fix: 세차장 등록 코드 수정
  src/main/java/bdbe/bdbd/carwash/CarwashRestController.java
  src/main/java/bdbe/bdbd/carwash/CarwashService.java
Labels: Priority: High

#153 fix: 사진 업로드 코드 수정
  src/main/java/bdbe/bdbd/_core/errors/config/AWSConfig.java
  src/main/java/bdbe/bdbd/_core/errors/utils/AwsS3Service.java
  src/main/java/bdbe/bdbd/carwash/CarwashRestController.java
  src/main/java/bdbe/bdbd/carwash/CarwashService.java
Labels: Priority: Urgent

#154 fix: 사진 업로드 코드 수정
  src/main/java/bdbe/bdbd/_core/errors/config/AWSConfig.java
  src/main/java/bdbe/bdbd/_core/errors/utils/AwsS3Service.java
  src/main/java/bdbe/bdbd/carwash/CarwashRestController.java
  src/main/java/bdbe/bdbd/carwash/CarwashService.java
Labels: Priority: High

#155 fix: 사진 업로드 코드 수정
  src/main/java/bdbe/bdbd/_core/errors/config/AWSConfig.java
  src/main/java/bdbe/bdbd/_core/errors/utils/AwsS3Service.java
  src/main/java/bdbe/bdbd/carwash/CarwashRestController.java
  src/main/java/bdbe/bdbd/carwash/CarwashService.java
Labels: Priority: High

#156 fix: 이미지 업로드 코드 수정
  build.gradle
  src/main/java/bdbe/bdbd/_core/errors/config/AWSConfig.java
  src/main/java/bdbe/bdbd/_core/errors/utils/AwsS3Service.java
  src/main/java/bdbe/bdbd/_core/errors/utils/S3ProxyUploadService.java
  src/main/java/bdbe/bdbd/carwash/CarwashService.java
Labels: Priority: High

#157 fix: 이미지 업로드 코드 수정
  build.gradle
  src/main/java/bdbe/bdbd/_core/errors/config/AWSConfig.java
  src/main/java/bdbe/bdbd/_core/errors/utils/AwsS3Service.java
  src/main/java/bdbe/bdbd/_core/errors/utils/S3ProxyUploadService.java
  src/main/java/bdbe/bdbd/carwash/CarwashService.java
Labels: Priority: High

#158 fix: 이미지 업로드 코드 수정
  build.gradle
  src/main/java/bdbe/bdbd/_core/errors/config/AWSConfig.java
  src/main/java/bdbe/bdbd/_core/errors/utils/AwsS3Service.java
  src/main/java/bdbe/bdbd/_core/errors/utils/S3ProxyUploadService.java
  src/main/java/bdbe/bdbd/carwash/CarwashService.java
Labels: Priority: High

#159 fix: 이미지 저장 코드 수정
  src/main/java/bdbe/bdbd/carwash/CarwashRestController.java
  src/main/java/bdbe/bdbd/carwash/CarwashService.java
  src/main/java/bdbe/bdbd/file/S3ProxyUploadService.java
Labels: Priority: High

#160 fix: 이미지 코드 수정
  src/main/java/bdbe/bdbd/carwash/CarwashRestController.java
  src/main/java/bdbe/bdbd/carwash/CarwashService.java
  src/main/java/bdbe/bdbd/file/S3ProxyUploadService.java
Labels: Priority: High

#161 fix: 이미지 코드 수정
  src/main/java/bdbe/bdbd/carwash/CarwashRestController.java
  src/main/java/bdbe/bdbd/carwash/CarwashService.java
  src/main/java/bdbe/bdbd/file/S3ProxyUploadService.java
Labels: Priority: High

#162 refactor: 이미지 부분 api 반영
  src/main/java/bdbe/bdbd/_core/errors/GlobalExceptionHandler.java
  src/main/java/bdbe/bdbd/carwash/CarwashResponse.java
  src/main/java/bdbe/bdbd/carwash/CarwashService.java
  src/main/java/bdbe/bdbd/file/FileJPARepository.java
  src/main/java/bdbe/bdbd/file/FileRestController.java
  src/main/java/bdbe/bdbd/member/OwnerResponse.java
  src/main/java/bdbe/bdbd/member/OwnerService.java
  src/main/java/bdbe/bdbd/reservation/ReservationResponse.java
  src/main/java/bdbe/bdbd/reservation/ReservationService.java
Labels: Priority: High

#163 feat: 결제 기능 구현
  src/main/java/bdbe/bdbd/_core/errors/config/RestTemplateConfig.java
  src/main/java/bdbe/bdbd/_core/errors/security/JwtAuthenticationFilter.java
  src/main/java/bdbe/bdbd/_core/errors/security/SecurityConfig.java
  src/main/java/bdbe/bdbd/file/FileJPARepository.java
  src/main/java/bdbe/bdbd/pay/PayController.java
  src/main/java/bdbe/bdbd/pay/PayRequest.java
  src/main/java/bdbe/bdbd/pay/PayResponse.java
  src/main/java/bdbe/bdbd/pay/PayService.java
  src/main/java/bdbe/bdbd/reservation/ReservationResponse.java
  src/main/java/bdbe/bdbd/reservation/ReservationRestController.java
  src/main/java/bdbe/bdbd/reservation/ReservationService.java
  src/test/java/bdbe/bdbd/pay/PayRestControllerTest.java
Labels: Type: Enhancement, Priority: Medium, Status: Done

#165 merge: from weekly to develop
  src/main/java/bdbe/bdbd/_core/errors/GlobalExceptionHandler.java
  src/main/java/bdbe/bdbd/_core/errors/config/RestTemplateConfig.java
  src/main/java/bdbe/bdbd/_core/errors/security/JwtAuthenticationFilter.java
  src/main/java/bdbe/bdbd/_core/errors/security/SecurityConfig.java
  src/main/java/bdbe/bdbd/carwash/CarwashResponse.java
  src/main/java/bdbe/bdbd/carwash/CarwashService.java
  src/main/java/bdbe/bdbd/file/FileJPARepository.java
  src/main/java/bdbe/bdbd/file/FileRestController.java
  src/main/java/bdbe/bdbd/member/OwnerResponse.java
  src/main/java/bdbe/bdbd/member/OwnerService.java
  src/main/java/bdbe/bdbd/pay/PayController.java
  src/main/java/bdbe/bdbd/pay/PayRequest.java
  src/main/java/bdbe/bdbd/pay/PayResponse.java
  src/main/java/bdbe/bdbd/pay/PayService.java
  src/main/java/bdbe/bdbd/reservation/ReservationResponse.java
  src/main/java/bdbe/bdbd/reservation/ReservationRestController.java
  src/main/java/bdbe/bdbd/reservation/ReservationService.java
  src/test/java/bdbe/bdbd/pay/PayRestControllerTest.java
Labels: Priority: High

#166 merge: from develop to main
  src/main/java/bdbe/bdbd/_core/errors/GlobalExceptionHandler.java
  src/main/java/bdbe/bdbd/_core/errors/config/RestTemplateConfig.java
  src/main/java/bdbe/bdbd/_core/errors/security/JwtAuthenticationFilter.java
  src/main/java/bdbe/bdbd/_core/errors/security/SecurityConfig.java
  src/main/java/bdbe/bdbd/carwash/CarwashResponse.java
  src/main/java/bdbe/bdbd/carwash/CarwashService.java
  src/main/java/bdbe/bdbd/file/FileJPARepository.java
  src/main/java/bdbe/bdbd/file/FileRestController.java
  src/main/java/bdbe/bdbd/member/OwnerResponse.java
  src/main/java/bdbe/bdbd/member/OwnerService.java
  src/main/java/bdbe/bdbd/pay/PayController.java
  src/main/java/bdbe/bdbd/pay/PayRequest.java
  src/main/java/bdbe/bdbd/pay/PayResponse.java
  src/main/java/bdbe/bdbd/pay/PayService.java
  src/main/java/bdbe/bdbd/reservation/ReservationResponse.java
  src/main/java/bdbe/bdbd/reservation/ReservationRestController.java
  src/main/java/bdbe/bdbd/reservation/ReservationService.java
  src/test/java/bdbe/bdbd/pay/PayRestControllerTest.java
Labels: Priority: High

#167 refactor: 위도, 경도 예외 처리 반영
  src/main/java/bdbe/bdbd/carwash/CarwashRequest.java
  src/main/java/bdbe/bdbd/carwash/CarwashRestController.java
  src/main/java/bdbe/bdbd/carwash/CarwashService.java
  src/main/java/bdbe/bdbd/location/Location.java
  src/main/java/bdbe/bdbd/member/OwnerResponse.java
  src/main/java/bdbe/bdbd/member/OwnerRestController.java
  src/main/java/bdbe/bdbd/member/OwnerService.java
  src/main/resources/application-prod.yml
Labels: Priority: High

#168 merge: from weekly to develop
  src/main/java/bdbe/bdbd/carwash/CarwashRequest.java
  src/main/java/bdbe/bdbd/carwash/CarwashRestController.java
  src/main/java/bdbe/bdbd/carwash/CarwashService.java
  src/main/java/bdbe/bdbd/location/Location.java
  src/main/java/bdbe/bdbd/member/OwnerResponse.java
  src/main/java/bdbe/bdbd/member/OwnerRestController.java
  src/main/java/bdbe/bdbd/member/OwnerService.java
  src/main/resources/application-prod.yml
Labels: Priority: Urgent

#169 merge: from develop to main
  src/main/java/bdbe/bdbd/carwash/CarwashRequest.java
  src/main/java/bdbe/bdbd/carwash/CarwashRestController.java
  src/main/java/bdbe/bdbd/carwash/CarwashService.java
  src/main/java/bdbe/bdbd/location/Location.java
  src/main/java/bdbe/bdbd/member/OwnerResponse.java
  src/main/java/bdbe/bdbd/member/OwnerRestController.java
  src/main/java/bdbe/bdbd/member/OwnerService.java
  src/main/resources/application-prod.yml
Labels: Priority: High

#170 chore: yaml 파일 설정
  src/main/java/bdbe/bdbd/member/OwnerResponse.java
  src/main/java/bdbe/bdbd/member/OwnerRestController.java
  src/main/java/bdbe/bdbd/member/OwnerService.java
  src/main/resources/application-prod.yml
Labels: Priority: High

#171 merge: from weekly to develop
  src/main/java/bdbe/bdbd/member/OwnerResponse.java
  src/main/java/bdbe/bdbd/member/OwnerRestController.java
  src/main/java/bdbe/bdbd/member/OwnerService.java
  src/main/resources/application-prod.yml
Labels: Priority: High

#172 merge: from develop to main
  src/main/java/bdbe/bdbd/member/OwnerResponse.java
  src/main/java/bdbe/bdbd/member/OwnerRestController.java
  src/main/java/bdbe/bdbd/member/OwnerService.java
  src/main/resources/application-prod.yml
Labels: Priority: High

#174 feat: 세차장 세부정보 수정에서 사용될 세차장 파일 삭제 기능
  src/main/java/bdbe/bdbd/carwash/CarwashResponse.java
  src/main/java/bdbe/bdbd/carwash/CarwashRestController.java
  src/main/java/bdbe/bdbd/file/File.java
  src/main/java/bdbe/bdbd/file/FileJPARepository.java
  src/main/java/bdbe/bdbd/file/FileRestController.java
  src/main/java/bdbe/bdbd/file/FileService.java
Labels: Type: Enhancement, Priority: Medium, Status: Done

#175 feat: 예약 목록 조회 기능 구현 및 등록 기능 수정
  src/main/java/bdbe/bdbd/carwash/CarwashRestController.java
  src/main/java/bdbe/bdbd/member/OwnerResponse.java
  src/main/java/bdbe/bdbd/member/OwnerRestController.java
  src/main/java/bdbe/bdbd/member/OwnerService.java
  src/main/java/bdbe/bdbd/reservation/ReservationJPARepository.java
Labels: Priority: High

#176 feat: 기능 개선 및 예외처리
  src/main/java/bdbe/bdbd/_core/errors/GlobalExceptionHandler.java
  src/main/java/bdbe/bdbd/_core/errors/exception/ForbiddenError.java
  src/main/java/bdbe/bdbd/_core/errors/exception/UnAuthorizedError.java
  src/main/java/bdbe/bdbd/_core/errors/security/CustomAuthenticationException.java
  src/main/java/bdbe/bdbd/_core/errors/security/JwtAuthenticationEntryPoint.java
  src/main/java/bdbe/bdbd/_core/errors/security/JwtAuthenticationFilter.java
  src/main/java/bdbe/bdbd/_core/errors/security/SecurityConfig.java
  src/main/java/bdbe/bdbd/_core/errors/utils/FileUploadUtil.java
  src/main/java/bdbe/bdbd/bay/BayRequest.java
  src/main/java/bdbe/bdbd/bay/BayRestController.java
  src/main/java/bdbe/bdbd/bay/BayService.java
  src/main/java/bdbe/bdbd/carwash/CarwashRestController.java
  src/main/java/bdbe/bdbd/carwash/CarwashService.java
  src/main/java/bdbe/bdbd/file/File.java
  src/main/java/bdbe/bdbd/file/FileRequest.java
  src/main/java/bdbe/bdbd/file/FileResponse.java
  src/main/java/bdbe/bdbd/member/OwnerService.java
  src/main/java/bdbe/bdbd/reservation/ReservationJPARepository.java
  src/main/java/bdbe/bdbd/reservation/ReservationResponse.java
  src/main/java/bdbe/bdbd/reservation/ReservationRestController.java
  src/main/java/bdbe/bdbd/reservation/ReservationService.java
  src/test/java/bdbe/bdbd/carwash/CarwashRestControllerTest.java
  src/test/java/bdbe/bdbd/file/FileRestControllerTest.java
  src/test/java/bdbe/bdbd/reservation/ReservationRestControllerTest.java
Labels: Priority: High

#177 merge: from weekly to develop (배포)
  src/main/java/bdbe/bdbd/_core/errors/GlobalExceptionHandler.java
  src/main/java/bdbe/bdbd/_core/errors/exception/ForbiddenError.java
  src/main/java/bdbe/bdbd/_core/errors/exception/UnAuthorizedError.java
  src/main/java/bdbe/bdbd/_core/errors/security/CustomAuthenticationException.java
  src/main/java/bdbe/bdbd/_core/errors/security/JwtAuthenticationEntryPoint.java
  src/main/java/bdbe/bdbd/_core/errors/security/JwtAuthenticationFilter.java
  src/main/java/bdbe/bdbd/_core/errors/security/SecurityConfig.java
  src/main/java/bdbe/bdbd/_core/errors/utils/FileUploadUtil.java
  src/main/java/bdbe/bdbd/bay/BayRequest.java
  src/main/java/bdbe/bdbd/bay/BayRestController.java
  src/main/java/bdbe/bdbd/bay/BayService.java
  src/main/java/bdbe/bdbd/carwash/CarwashResponse.java
  src/main/java/bdbe/bdbd/carwash/CarwashRestController.java
  src/main/java/bdbe/bdbd/carwash/CarwashService.java
  src/main/java/bdbe/bdbd/file/File.java
  src/main/java/bdbe/bdbd/file/FileJPARepository.java
  src/main/java/bdbe/bdbd/file/FileRequest.java
  src/main/java/bdbe/bdbd/file/FileResponse.java
  src/main/java/bdbe/bdbd/file/FileRestController.java
  src/main/java/bdbe/bdbd/file/FileService.java
  src/main/java/bdbe/bdbd/member/OwnerResponse.java
  src/main/java/bdbe/bdbd/member/OwnerRestController.java
  src/main/java/bdbe/bdbd/member/OwnerService.java
  src/main/java/bdbe/bdbd/reservation/ReservationJPARepository.java
  src/main/java/bdbe/bdbd/reservation/ReservationResponse.java
  src/main/java/bdbe/bdbd/reservation/ReservationRestController.java
  src/main/java/bdbe/bdbd/reservation/ReservationService.java
  src/test/java/bdbe/bdbd/carwash/CarwashRestControllerTest.java
  src/test/java/bdbe/bdbd/file/FileRestControllerTest.java
  src/test/java/bdbe/bdbd/reservation/ReservationRestControllerTest.java
Labels: Priority: High

#178 merge: from develop to main (배포)
  src/main/java/bdbe/bdbd/_core/errors/GlobalExceptionHandler.java
  src/main/java/bdbe/bdbd/_core/errors/exception/ForbiddenError.java
  src/main/java/bdbe/bdbd/_core/errors/exception/UnAuthorizedError.java
  src/main/java/bdbe/bdbd/_core/errors/security/CustomAuthenticationException.java
  src/main/java/bdbe/bdbd/_core/errors/security/JwtAuthenticationEntryPoint.java
  src/main/java/bdbe/bdbd/_core/errors/security/JwtAuthenticationFilter.java
  src/main/java/bdbe/bdbd/_core/errors/security/SecurityConfig.java
  src/main/java/bdbe/bdbd/_core/errors/utils/FileUploadUtil.java
  src/main/java/bdbe/bdbd/bay/BayRequest.java
  src/main/java/bdbe/bdbd/bay/BayRestController.java
  src/main/java/bdbe/bdbd/bay/BayService.java
  src/main/java/bdbe/bdbd/carwash/CarwashResponse.java
  src/main/java/bdbe/bdbd/carwash/CarwashRestController.java
  src/main/java/bdbe/bdbd/carwash/CarwashService.java
  src/main/java/bdbe/bdbd/file/File.java
  src/main/java/bdbe/bdbd/file/FileJPARepository.java
  src/main/java/bdbe/bdbd/file/FileRequest.java
  src/main/java/bdbe/bdbd/file/FileResponse.java
  src/main/java/bdbe/bdbd/file/FileRestController.java
  src/main/java/bdbe/bdbd/file/FileService.java
  src/main/java/bdbe/bdbd/member/OwnerResponse.java
  src/main/java/bdbe/bdbd/member/OwnerRestController.java
  src/main/java/bdbe/bdbd/member/OwnerService.java
  src/main/java/bdbe/bdbd/reservation/ReservationJPARepository.java
  src/main/java/bdbe/bdbd/reservation/ReservationResponse.java
  src/main/java/bdbe/bdbd/reservation/ReservationRestController.java
  src/main/java/bdbe/bdbd/reservation/ReservationService.java
  src/test/java/bdbe/bdbd/carwash/CarwashRestControllerTest.java
  src/test/java/bdbe/bdbd/file/FileRestControllerTest.java
  src/test/java/bdbe/bdbd/reservation/ReservationRestControllerTest.java
Labels: Priority: High

#179 refactor:기능 개선 및 버그 수정을 위한 코드 리팩토링
  src/main/java/bdbe/bdbd/member/OwnerResponse.java
  src/main/java/bdbe/bdbd/member/OwnerService.java
  src/main/java/bdbe/bdbd/reservation/ReservationResponse.java
Labels: Priority: High

#181 feat: 파일 업로드 및 세차장 상세 관리 기능 업데이트 및 수정
  src/main/java/bdbe/bdbd/carwash/CarwashResponse.java
  src/main/java/bdbe/bdbd/carwash/CarwashRestController.java
  src/main/java/bdbe/bdbd/carwash/CarwashService.java
  src/main/java/bdbe/bdbd/file/S3ProxyUploadService.java
  src/main/java/bdbe/bdbd/member/OwnerResponse.java
  src/main/java/bdbe/bdbd/member/OwnerService.java
  src/main/java/bdbe/bdbd/reservation/ReservationResponse.java
  src/test/java/bdbe/bdbd/carwash/CarwashRestControllerTest.java
Labels: Type: Enhancement, Priority: Medium, Status: Done

#183 feat: 사용자 정보 및 결제 금액 조회 기능 추가, 에러 핸들링 개선
  src/main/java/bdbe/bdbd/bay/BayRequest.java
  src/main/java/bdbe/bdbd/bay/BayRestController.java
  src/main/java/bdbe/bdbd/bay/BayService.java
  src/main/java/bdbe/bdbd/carwash/CarwashResponse.java
  src/main/java/bdbe/bdbd/carwash/CarwashRestController.java
  src/main/java/bdbe/bdbd/carwash/CarwashService.java
  src/main/java/bdbe/bdbd/file/FileJPARepository.java
  src/main/java/bdbe/bdbd/member/Member.java
  src/main/java/bdbe/bdbd/member/MemberRestController.java
  src/main/java/bdbe/bdbd/member/MemberService.java
  src/main/java/bdbe/bdbd/member/OwnerResponse.java
  src/main/java/bdbe/bdbd/member/OwnerRestController.java
  src/main/java/bdbe/bdbd/member/OwnerService.java
  src/main/java/bdbe/bdbd/pay/PayController.java
  src/main/java/bdbe/bdbd/pay/PayService.java
  src/main/java/bdbe/bdbd/reservation/ReservationJPARepository.java
  src/main/java/bdbe/bdbd/reservation/ReservationRequest.java
  src/main/java/bdbe/bdbd/reservation/ReservationResponse.java
  src/main/java/bdbe/bdbd/reservation/ReservationRestController.java
  src/main/java/bdbe/bdbd/reservation/ReservationService.java
  src/test/java/bdbe/bdbd/carwash/CarwashRestControllerTest.java
Labels: Priority: High

#184 merge: from weekly to develop
  src/main/java/bdbe/bdbd/bay/BayRequest.java
  src/main/java/bdbe/bdbd/bay/BayRestController.java
  src/main/java/bdbe/bdbd/bay/BayService.java
  src/main/java/bdbe/bdbd/carwash/CarwashResponse.java
  src/main/java/bdbe/bdbd/carwash/CarwashRestController.java
  src/main/java/bdbe/bdbd/carwash/CarwashService.java
  src/main/java/bdbe/bdbd/file/FileJPARepository.java
  src/main/java/bdbe/bdbd/file/S3ProxyUploadService.java
  src/main/java/bdbe/bdbd/member/Member.java
  src/main/java/bdbe/bdbd/member/MemberRestController.java
  src/main/java/bdbe/bdbd/member/MemberService.java
  src/main/java/bdbe/bdbd/member/OwnerResponse.java
  src/main/java/bdbe/bdbd/member/OwnerRestController.java
  src/main/java/bdbe/bdbd/member/OwnerService.java
  src/main/java/bdbe/bdbd/pay/PayController.java
  src/main/java/bdbe/bdbd/pay/PayService.java
  src/main/java/bdbe/bdbd/reservation/ReservationJPARepository.java
  src/main/java/bdbe/bdbd/reservation/ReservationRequest.java
  src/main/java/bdbe/bdbd/reservation/ReservationResponse.java
  src/main/java/bdbe/bdbd/reservation/ReservationRestController.java
  src/main/java/bdbe/bdbd/reservation/ReservationService.java
  src/test/java/bdbe/bdbd/carwash/CarwashRestControllerTest.java
Labels: Priority: High

#185 merge: from develop to main
  src/main/java/bdbe/bdbd/bay/BayRequest.java
  src/main/java/bdbe/bdbd/bay/BayRestController.java
  src/main/java/bdbe/bdbd/bay/BayService.java
  src/main/java/bdbe/bdbd/carwash/CarwashResponse.java
  src/main/java/bdbe/bdbd/carwash/CarwashRestController.java
  src/main/java/bdbe/bdbd/carwash/CarwashService.java
  src/main/java/bdbe/bdbd/file/FileJPARepository.java
  src/main/java/bdbe/bdbd/file/S3ProxyUploadService.java
  src/main/java/bdbe/bdbd/member/Member.java
  src/main/java/bdbe/bdbd/member/MemberRestController.java
  src/main/java/bdbe/bdbd/member/MemberService.java
  src/main/java/bdbe/bdbd/member/OwnerResponse.java
  src/main/java/bdbe/bdbd/member/OwnerRestController.java
  src/main/java/bdbe/bdbd/member/OwnerService.java
  src/main/java/bdbe/bdbd/pay/PayController.java
  src/main/java/bdbe/bdbd/pay/PayService.java
  src/main/java/bdbe/bdbd/reservation/ReservationJPARepository.java
  src/main/java/bdbe/bdbd/reservation/ReservationRequest.java
  src/main/java/bdbe/bdbd/reservation/ReservationResponse.java
  src/main/java/bdbe/bdbd/reservation/ReservationRestController.java
  src/main/java/bdbe/bdbd/reservation/ReservationService.java
  src/test/java/bdbe/bdbd/carwash/CarwashRestControllerTest.java
Labels: Priority: High

#188 refactor: 코드 정리 및 설정 값 상수화
  src/main/java/bdbe/bdbd/_core/errors/config/RestTemplateConfig.java
  src/main/java/bdbe/bdbd/_core/errors/security/CustomAuthenticationException.java
  src/main/java/bdbe/bdbd/_core/errors/security/JWTProvider.java
  src/main/java/bdbe/bdbd/_core/errors/security/JwtAuthenticationEntryPoint.java
  src/main/java/bdbe/bdbd/_core/errors/security/JwtAuthenticationFilter.java
  src/main/java/bdbe/bdbd/_core/errors/security/SecurityConfig.java
  src/main/java/bdbe/bdbd/_core/errors/utils/FileUploadUtil.java
  src/main/java/bdbe/bdbd/bay/Bay.java
  src/main/java/bdbe/bdbd/bay/BayJPARepository.java
  src/main/java/bdbe/bdbd/bay/BayRequest.java
  src/main/java/bdbe/bdbd/bay/BayResponse.java
  src/main/java/bdbe/bdbd/bay/BayRestController.java
  src/main/java/bdbe/bdbd/bay/BayService.java
  src/main/java/bdbe/bdbd/carwash/Carwash.java
  src/main/java/bdbe/bdbd/carwash/CarwashJPARepository.java
  src/main/java/bdbe/bdbd/carwash/CarwashRequest.java
  src/main/java/bdbe/bdbd/carwash/CarwashResponse.java
  src/main/java/bdbe/bdbd/carwash/CarwashRestController.java
  src/main/java/bdbe/bdbd/carwash/CarwashService.java
  src/main/java/bdbe/bdbd/file/File.java
  src/main/java/bdbe/bdbd/file/FileRequest.java
  src/main/java/bdbe/bdbd/file/FileResponse.java
  src/main/java/bdbe/bdbd/file/FileRestController.java
  src/main/java/bdbe/bdbd/file/FileService.java
  src/main/java/bdbe/bdbd/keyword/KeywordType.java
  src/main/java/bdbe/bdbd/keyword/carwashKeyword/CarwashKeyword.java
  src/main/java/bdbe/bdbd/keyword/reviewKeyword/ReviewKeywordJPARepository.java
  src/main/java/bdbe/bdbd/location/Location.java
  src/main/java/bdbe/bdbd/member/MemberRequest.java
  src/main/java/bdbe/bdbd/member/MemberRestController.java
  src/main/java/bdbe/bdbd/member/MemberService.java
  src/main/java/bdbe/bdbd/member/OwnerRequest.java
  src/main/java/bdbe/bdbd/member/OwnerResponse.java
  src/main/java/bdbe/bdbd/member/OwnerRestController.java
  src/main/java/bdbe/bdbd/member/OwnerService.java
  src/main/java/bdbe/bdbd/optime/Optime.java
  src/main/java/bdbe/bdbd/pay/PayResponse.java
  src/main/java/bdbe/bdbd/pay/PayService.java
  src/main/java/bdbe/bdbd/reservation/Reservation.java
  src/main/java/bdbe/bdbd/reservation/ReservationJPARepository.java
  src/main/java/bdbe/bdbd/reservation/ReservationResponse.java
  src/main/java/bdbe/bdbd/reservation/ReservationRestController.java
  src/main/java/bdbe/bdbd/reservation/ReservationService.java
  src/main/java/bdbe/bdbd/review/Review.java
  src/main/java/bdbe/bdbd/review/ReviewJPARepository.java
  src/main/java/bdbe/bdbd/review/ReviewRestController.java
  src/main/java/bdbe/bdbd/review/ReviewService.java
  src/test/java/bdbe/bdbd/bay/BayRestControllerTest.java
  src/test/java/bdbe/bdbd/carwash/CarwashRestControllerTest.java
  src/test/java/bdbe/bdbd/file/FileRestControllerTest.java
  src/test/java/bdbe/bdbd/member/MemberRestControllerTest.java
  src/test/java/bdbe/bdbd/member/OwnerRestControllerTest.java
  src/test/java/bdbe/bdbd/pay/PayRestControllerTest.java
  src/test/java/bdbe/bdbd/reservation/ReservationRestControllerTest.java
  src/test/java/bdbe/bdbd/review/ReviewRestControllerTest.java
Labels: Priority: High

#189 refactor: 코드 정리 및 설정 값 상수화 작업
  src/main/java/bdbe/bdbd/_core/errors/config/RestTemplateConfig.java
  src/main/java/bdbe/bdbd/_core/errors/security/CustomAuthenticationException.java
  src/main/java/bdbe/bdbd/_core/errors/security/JWTProvider.java
  src/main/java/bdbe/bdbd/_core/errors/security/JwtAuthenticationEntryPoint.java
  src/main/java/bdbe/bdbd/_core/errors/security/JwtAuthenticationFilter.java
  src/main/java/bdbe/bdbd/_core/errors/security/SecurityConfig.java
  src/main/java/bdbe/bdbd/_core/errors/utils/FileUploadUtil.java
  src/main/java/bdbe/bdbd/bay/Bay.java
  src/main/java/bdbe/bdbd/bay/BayJPARepository.java
  src/main/java/bdbe/bdbd/bay/BayRequest.java
  src/main/java/bdbe/bdbd/bay/BayResponse.java
  src/main/java/bdbe/bdbd/bay/BayRestController.java
  src/main/java/bdbe/bdbd/bay/BayService.java
  src/main/java/bdbe/bdbd/carwash/Carwash.java
  src/main/java/bdbe/bdbd/carwash/CarwashJPARepository.java
  src/main/java/bdbe/bdbd/carwash/CarwashRequest.java
  src/main/java/bdbe/bdbd/carwash/CarwashResponse.java
  src/main/java/bdbe/bdbd/carwash/CarwashRestController.java
  src/main/java/bdbe/bdbd/carwash/CarwashService.java
  src/main/java/bdbe/bdbd/file/File.java
  src/main/java/bdbe/bdbd/file/FileRequest.java
  src/main/java/bdbe/bdbd/file/FileResponse.java
  src/main/java/bdbe/bdbd/file/FileRestController.java
  src/main/java/bdbe/bdbd/file/FileService.java
  src/main/java/bdbe/bdbd/keyword/KeywordType.java
  src/main/java/bdbe/bdbd/keyword/carwashKeyword/CarwashKeyword.java
  src/main/java/bdbe/bdbd/keyword/reviewKeyword/ReviewKeywordJPARepository.java
  src/main/java/bdbe/bdbd/location/Location.java
  src/main/java/bdbe/bdbd/member/MemberRequest.java
  src/main/java/bdbe/bdbd/member/MemberRestController.java
  src/main/java/bdbe/bdbd/member/MemberService.java
  src/main/java/bdbe/bdbd/member/OwnerRequest.java
  src/main/java/bdbe/bdbd/member/OwnerResponse.java
  src/main/java/bdbe/bdbd/member/OwnerRestController.java
  src/main/java/bdbe/bdbd/member/OwnerService.java
  src/main/java/bdbe/bdbd/optime/Optime.java
  src/main/java/bdbe/bdbd/pay/PayResponse.java
  src/main/java/bdbe/bdbd/pay/PayService.java
  src/main/java/bdbe/bdbd/reservation/Reservation.java
  src/main/java/bdbe/bdbd/reservation/ReservationJPARepository.java
  src/main/java/bdbe/bdbd/reservation/ReservationResponse.java
  src/main/java/bdbe/bdbd/reservation/ReservationRestController.java
  src/main/java/bdbe/bdbd/reservation/ReservationService.java
  src/main/java/bdbe/bdbd/review/Review.java
  src/main/java/bdbe/bdbd/review/ReviewJPARepository.java
  src/main/java/bdbe/bdbd/review/ReviewRestController.java
  src/main/java/bdbe/bdbd/review/ReviewService.java
  src/test/java/bdbe/bdbd/bay/BayRestControllerTest.java
  src/test/java/bdbe/bdbd/carwash/CarwashRestControllerTest.java
  src/test/java/bdbe/bdbd/file/FileRestControllerTest.java
  src/test/java/bdbe/bdbd/member/MemberRestControllerTest.java
  src/test/java/bdbe/bdbd/member/OwnerRestControllerTest.java
  src/test/java/bdbe/bdbd/pay/PayRestControllerTest.java
  src/test/java/bdbe/bdbd/reservation/ReservationRestControllerTest.java
  src/test/java/bdbe/bdbd/review/ReviewRestControllerTest.java
Labels: Priority: High

#190 refactor: 코드 정리 및 설정 값 상수화 작업
  src/main/java/bdbe/bdbd/_core/errors/config/RestTemplateConfig.java
  src/main/java/bdbe/bdbd/_core/errors/security/CustomAuthenticationException.java
  src/main/java/bdbe/bdbd/_core/errors/security/JWTProvider.java
  src/main/java/bdbe/bdbd/_core/errors/security/JwtAuthenticationEntryPoint.java
  src/main/java/bdbe/bdbd/_core/errors/security/JwtAuthenticationFilter.java
  src/main/java/bdbe/bdbd/_core/errors/security/SecurityConfig.java
  src/main/java/bdbe/bdbd/_core/errors/utils/FileUploadUtil.java
  src/main/java/bdbe/bdbd/bay/Bay.java
  src/main/java/bdbe/bdbd/bay/BayJPARepository.java
  src/main/java/bdbe/bdbd/bay/BayRequest.java
  src/main/java/bdbe/bdbd/bay/BayResponse.java
  src/main/java/bdbe/bdbd/bay/BayRestController.java
  src/main/java/bdbe/bdbd/bay/BayService.java
  src/main/java/bdbe/bdbd/carwash/Carwash.java
  src/main/java/bdbe/bdbd/carwash/CarwashJPARepository.java
  src/main/java/bdbe/bdbd/carwash/CarwashRequest.java
  src/main/java/bdbe/bdbd/carwash/CarwashResponse.java
  src/main/java/bdbe/bdbd/carwash/CarwashRestController.java
  src/main/java/bdbe/bdbd/carwash/CarwashService.java
  src/main/java/bdbe/bdbd/file/File.java
  src/main/java/bdbe/bdbd/file/FileRequest.java
  src/main/java/bdbe/bdbd/file/FileResponse.java
  src/main/java/bdbe/bdbd/file/FileRestController.java
  src/main/java/bdbe/bdbd/file/FileService.java
  src/main/java/bdbe/bdbd/keyword/KeywordType.java
  src/main/java/bdbe/bdbd/keyword/carwashKeyword/CarwashKeyword.java
  src/main/java/bdbe/bdbd/keyword/reviewKeyword/ReviewKeywordJPARepository.java
  src/main/java/bdbe/bdbd/location/Location.java
  src/main/java/bdbe/bdbd/member/MemberRequest.java
  src/main/java/bdbe/bdbd/member/MemberRestController.java
  src/main/java/bdbe/bdbd/member/MemberService.java
  src/main/java/bdbe/bdbd/member/OwnerRequest.java
  src/main/java/bdbe/bdbd/member/OwnerResponse.java
  src/main/java/bdbe/bdbd/member/OwnerRestController.java
  src/main/java/bdbe/bdbd/member/OwnerService.java
  src/main/java/bdbe/bdbd/optime/Optime.java
  src/main/java/bdbe/bdbd/pay/PayResponse.java
  src/main/java/bdbe/bdbd/pay/PayService.java
  src/main/java/bdbe/bdbd/reservation/Reservation.java
  src/main/java/bdbe/bdbd/reservation/ReservationJPARepository.java
  src/main/java/bdbe/bdbd/reservation/ReservationResponse.java
  src/main/java/bdbe/bdbd/reservation/ReservationRestController.java
  src/main/java/bdbe/bdbd/reservation/ReservationService.java
  src/main/java/bdbe/bdbd/review/Review.java
  src/main/java/bdbe/bdbd/review/ReviewJPARepository.java
  src/main/java/bdbe/bdbd/review/ReviewRestController.java
  src/main/java/bdbe/bdbd/review/ReviewService.java
  src/test/java/bdbe/bdbd/bay/BayRestControllerTest.java
  src/test/java/bdbe/bdbd/carwash/CarwashRestControllerTest.java
  src/test/java/bdbe/bdbd/file/FileRestControllerTest.java
  src/test/java/bdbe/bdbd/member/MemberRestControllerTest.java
  src/test/java/bdbe/bdbd/member/OwnerRestControllerTest.java
  src/test/java/bdbe/bdbd/pay/PayRestControllerTest.java
  src/test/java/bdbe/bdbd/reservation/ReservationRestControllerTest.java
  src/test/java/bdbe/bdbd/review/ReviewRestControllerTest.java
Labels: Priority: High

#194 refactor: config 코드 수정
  src/main/java/bdbe/bdbd/_core/errors/config/RestTemplateConfig.java
Labels: Priority: High

#195 fix: 사용자 이름 조회 get 요청으로 변경
  src/main/java/bdbe/bdbd/member/MemberRestController.java
Labels: Priority: High

#196 merge: from weekly to develop (배포)
  src/main/java/bdbe/bdbd/member/MemberRestController.java
Labels: Priority: High

#197 merge: from develop to main
  src/main/java/bdbe/bdbd/member/MemberRestController.java
Labels: Priority: High

#198 feat: 로그아웃 기능 및 토큰 캐싱과 스케쥴링 설정 구현
  build.gradle
  src/main/java/bdbe/bdbd/BdbdApplication.java
  src/main/java/bdbe/bdbd/_core/errors/config/CacheConfig.java
  src/main/java/bdbe/bdbd/_core/errors/security/CacheService.java
  src/main/java/bdbe/bdbd/_core/errors/security/JwtAuthenticationFilter.java
  src/main/java/bdbe/bdbd/_core/errors/security/ScheduledTasks.java
  src/main/java/bdbe/bdbd/_core/errors/security/SecurityConfig.java
  src/main/java/bdbe/bdbd/member/MemberResponse.java
  src/main/java/bdbe/bdbd/member/MemberRestController.java
  src/main/java/bdbe/bdbd/member/OwnerRestController.java
  src/test/java/bdbe/bdbd/member/MemberRestControllerTest.java
Labels: Type: Enhancement, Priority: Medium, Request Review

#199 Revert "feat: 로그아웃 기능 및 토큰 캐싱과 스케쥴링 설정 구현"
  build.gradle
  src/main/java/bdbe/bdbd/BdbdApplication.java
  src/main/java/bdbe/bdbd/_core/errors/config/CacheConfig.java
  src/main/java/bdbe/bdbd/_core/errors/security/CacheService.java
  src/main/java/bdbe/bdbd/_core/errors/security/JwtAuthenticationFilter.java
  src/main/java/bdbe/bdbd/_core/errors/security/ScheduledTasks.java
  src/main/java/bdbe/bdbd/_core/errors/security/SecurityConfig.java
  src/main/java/bdbe/bdbd/member/MemberResponse.java
  src/main/java/bdbe/bdbd/member/MemberRestController.java
  src/main/java/bdbe/bdbd/member/OwnerRestController.java
  src/test/java/bdbe/bdbd/member/MemberRestControllerTest.java
Labels: Priority: Urgent

#200 refactor: 응답 포맷 일관성 개선
  src/main/java/bdbe/bdbd/_core/errors/GlobalExceptionHandler.java
  src/main/java/bdbe/bdbd/_core/errors/utils/DateUtils.java
  src/main/java/bdbe/bdbd/bay/BayService.java
  src/main/java/bdbe/bdbd/carwash/CarwashResponse.java
  src/main/java/bdbe/bdbd/carwash/CarwashService.java
  src/main/java/bdbe/bdbd/file/FileService.java
  src/main/java/bdbe/bdbd/member/MemberRequest.java
  src/main/java/bdbe/bdbd/member/OwnerResponse.java
  src/main/java/bdbe/bdbd/reservation/ReservationResponse.java
  src/main/java/bdbe/bdbd/reservation/ReservationService.java
  src/main/java/bdbe/bdbd/review/ReviewRequest.java
Labels: Priority: High

#201 merge: from weekly to develop (배포)
  src/main/java/bdbe/bdbd/_core/errors/GlobalExceptionHandler.java
  src/main/java/bdbe/bdbd/_core/errors/utils/DateUtils.java
  src/main/java/bdbe/bdbd/bay/BayService.java
  src/main/java/bdbe/bdbd/carwash/CarwashResponse.java
  src/main/java/bdbe/bdbd/carwash/CarwashService.java
  src/main/java/bdbe/bdbd/file/FileService.java
  src/main/java/bdbe/bdbd/member/MemberRequest.java
  src/main/java/bdbe/bdbd/member/OwnerResponse.java
  src/main/java/bdbe/bdbd/reservation/ReservationResponse.java
  src/main/java/bdbe/bdbd/reservation/ReservationService.java
  src/main/java/bdbe/bdbd/review/ReviewRequest.java
Labels: Priority: High

#204 merge: from weekly to develop
  src/test/java/bdbe/bdbd/reservation/ReservationRestControllerTest.java
Labels: Priority: Urgent

#205 merge: from develop to main
  src/test/java/bdbe/bdbd/reservation/ReservationRestControllerTest.java
Labels: Priority: Urgent

#206 resolve: 충돌 해결
  README.md
  src/main/java/bdbe/bdbd/_core/errors/config/RestTemplateConfig.java
  src/main/java/bdbe/bdbd/_core/errors/security/CustomAuthenticationException.java
  src/main/java/bdbe/bdbd/_core/errors/security/CustomUserDetailsService.java
  src/main/java/bdbe/bdbd/_core/errors/security/JWTProvider.java
  src/main/java/bdbe/bdbd/_core/errors/security/JwtAuthenticationEntryPoint.java
  src/main/java/bdbe/bdbd/_core/errors/security/JwtAuthenticationFilter.java
  src/main/java/bdbe/bdbd/_core/errors/security/SecurityConfig.java
  src/main/java/bdbe/bdbd/_core/errors/utils/FileUploadUtil.java
  src/main/java/bdbe/bdbd/bay/Bay.java
  src/main/java/bdbe/bdbd/bay/BayJPARepository.java
  src/main/java/bdbe/bdbd/bay/BayRequest.java
  src/main/java/bdbe/bdbd/bay/BayResponse.java
  src/main/java/bdbe/bdbd/bay/BayRestController.java
  src/main/java/bdbe/bdbd/bay/BayService.java
  src/main/java/bdbe/bdbd/carwash/Carwash.java
  src/main/java/bdbe/bdbd/carwash/CarwashJPARepository.java
  src/main/java/bdbe/bdbd/carwash/CarwashRequest.java
  src/main/java/bdbe/bdbd/carwash/CarwashResponse.java
  src/main/java/bdbe/bdbd/carwash/CarwashRestController.java
  src/main/java/bdbe/bdbd/carwash/CarwashService.java
  src/main/java/bdbe/bdbd/file/File.java
  src/main/java/bdbe/bdbd/file/FileRequest.java
  src/main/java/bdbe/bdbd/file/FileResponse.java
  src/main/java/bdbe/bdbd/file/FileRestController.java
  src/main/java/bdbe/bdbd/file/FileService.java
  src/main/java/bdbe/bdbd/keyword/KeywordType.java
  src/main/java/bdbe/bdbd/keyword/carwashKeyword/CarwashKeyword.java
  src/main/java/bdbe/bdbd/keyword/reviewKeyword/ReviewKeywordJPARepository.java
  src/main/java/bdbe/bdbd/location/Location.java
  src/main/java/bdbe/bdbd/member/MemberRequest.java
  src/main/java/bdbe/bdbd/member/MemberRestController.java
  src/main/java/bdbe/bdbd/member/MemberService.java
  src/main/java/bdbe/bdbd/member/OwnerRequest.java
  src/main/java/bdbe/bdbd/member/OwnerResponse.java
  src/main/java/bdbe/bdbd/member/OwnerRestController.java
  src/main/java/bdbe/bdbd/member/OwnerService.java
  src/main/java/bdbe/bdbd/optime/Optime.java
  src/main/java/bdbe/bdbd/pay/PayController.java
  src/main/java/bdbe/bdbd/pay/PayResponse.java
  src/main/java/bdbe/bdbd/pay/PayService.java
  src/main/java/bdbe/bdbd/reservation/Reservation.java
  src/main/java/bdbe/bdbd/reservation/ReservationJPARepository.java
  src/main/java/bdbe/bdbd/reservation/ReservationResponse.java
  src/main/java/bdbe/bdbd/reservation/ReservationRestController.java
  src/main/java/bdbe/bdbd/reservation/ReservationService.java
  src/main/java/bdbe/bdbd/review/Review.java
  src/main/java/bdbe/bdbd/review/ReviewJPARepository.java
  src/main/java/bdbe/bdbd/review/ReviewResponse.java
  src/main/java/bdbe/bdbd/review/ReviewRestController.java
  src/main/java/bdbe/bdbd/review/ReviewService.java
  src/test/java/bdbe/bdbd/bay/BayRestControllerTest.java
  src/test/java/bdbe/bdbd/carwash/CarwashRestControllerTest.java
  src/test/java/bdbe/bdbd/file/FileRestControllerTest.java
  src/test/java/bdbe/bdbd/member/MemberRestControllerTest.java
  src/test/java/bdbe/bdbd/member/OwnerRestControllerTest.java
  src/test/java/bdbe/bdbd/pay/PayRestControllerTest.java
  src/test/java/bdbe/bdbd/reservation/ReservationRestControllerTest.java
  src/test/java/bdbe/bdbd/review/ReviewRestControllerTest.java
Labels: Priority: Urgent

#207 resolve: 충돌 해결
  README.md
  src/main/java/bdbe/bdbd/_core/errors/config/RestTemplateConfig.java
  src/main/java/bdbe/bdbd/_core/errors/security/CustomAuthenticationException.java
  src/main/java/bdbe/bdbd/_core/errors/security/CustomUserDetailsService.java
  src/main/java/bdbe/bdbd/_core/errors/security/JWTProvider.java
  src/main/java/bdbe/bdbd/_core/errors/security/JwtAuthenticationEntryPoint.java
  src/main/java/bdbe/bdbd/_core/errors/security/JwtAuthenticationFilter.java
  src/main/java/bdbe/bdbd/_core/errors/security/SecurityConfig.java
  src/main/java/bdbe/bdbd/_core/errors/utils/FileUploadUtil.java
  src/main/java/bdbe/bdbd/bay/Bay.java
  src/main/java/bdbe/bdbd/bay/BayJPARepository.java
  src/main/java/bdbe/bdbd/bay/BayRequest.java
  src/main/java/bdbe/bdbd/bay/BayResponse.java
  src/main/java/bdbe/bdbd/bay/BayRestController.java
  src/main/java/bdbe/bdbd/bay/BayService.java
  src/main/java/bdbe/bdbd/carwash/Carwash.java
  src/main/java/bdbe/bdbd/carwash/CarwashJPARepository.java
  src/main/java/bdbe/bdbd/carwash/CarwashRequest.java
  src/main/java/bdbe/bdbd/carwash/CarwashResponse.java
  src/main/java/bdbe/bdbd/carwash/CarwashRestController.java
  src/main/java/bdbe/bdbd/carwash/CarwashService.java
  src/main/java/bdbe/bdbd/file/File.java
  src/main/java/bdbe/bdbd/file/FileRequest.java
  src/main/java/bdbe/bdbd/file/FileResponse.java
  src/main/java/bdbe/bdbd/file/FileRestController.java
  src/main/java/bdbe/bdbd/file/FileService.java
  src/main/java/bdbe/bdbd/keyword/KeywordType.java
  src/main/java/bdbe/bdbd/keyword/carwashKeyword/CarwashKeyword.java
  src/main/java/bdbe/bdbd/keyword/reviewKeyword/ReviewKeywordJPARepository.java
  src/main/java/bdbe/bdbd/location/Location.java
  src/main/java/bdbe/bdbd/member/MemberRequest.java
  src/main/java/bdbe/bdbd/member/MemberRestController.java
  src/main/java/bdbe/bdbd/member/MemberService.java
  src/main/java/bdbe/bdbd/member/OwnerRequest.java
  src/main/java/bdbe/bdbd/member/OwnerResponse.java
  src/main/java/bdbe/bdbd/member/OwnerRestController.java
  src/main/java/bdbe/bdbd/member/OwnerService.java
  src/main/java/bdbe/bdbd/optime/Optime.java
  src/main/java/bdbe/bdbd/pay/PayController.java
  src/main/java/bdbe/bdbd/pay/PayResponse.java
  src/main/java/bdbe/bdbd/pay/PayService.java
  src/main/java/bdbe/bdbd/reservation/Reservation.java
  src/main/java/bdbe/bdbd/reservation/ReservationJPARepository.java
  src/main/java/bdbe/bdbd/reservation/ReservationResponse.java
  src/main/java/bdbe/bdbd/reservation/ReservationRestController.java
  src/main/java/bdbe/bdbd/reservation/ReservationService.java
  src/main/java/bdbe/bdbd/review/Review.java
  src/main/java/bdbe/bdbd/review/ReviewJPARepository.java
  src/main/java/bdbe/bdbd/review/ReviewResponse.java
  src/main/java/bdbe/bdbd/review/ReviewRestController.java
  src/main/java/bdbe/bdbd/review/ReviewService.java
  src/test/java/bdbe/bdbd/bay/BayRestControllerTest.java
  src/test/java/bdbe/bdbd/carwash/CarwashRestControllerTest.java
  src/test/java/bdbe/bdbd/file/FileRestControllerTest.java
  src/test/java/bdbe/bdbd/member/MemberRestControllerTest.java
  src/test/java/bdbe/bdbd/member/OwnerRestControllerTest.java
  src/test/java/bdbe/bdbd/pay/PayRestControllerTest.java
  src/test/java/bdbe/bdbd/reservation/ReservationRestControllerTest.java
  src/test/java/bdbe/bdbd/review/ReviewRestControllerTest.java
Labels: Priority: Urgent

#208 fix: 로그아웃 기능 정상 작동 하게끔 코드 수정
  build.gradle
  src/main/java/bdbe/bdbd/BdbdApplication.java
  src/main/java/bdbe/bdbd/_core/errors/config/CacheConfig.java
  src/main/java/bdbe/bdbd/_core/errors/security/CacheService.java
  src/main/java/bdbe/bdbd/_core/errors/security/JWTProvider.java
  src/main/java/bdbe/bdbd/_core/errors/security/JwtAuthenticationFilter.java
  src/main/java/bdbe/bdbd/_core/errors/security/ScheduledTasks.java
  src/main/java/bdbe/bdbd/_core/errors/security/SecurityConfig.java
  src/main/java/bdbe/bdbd/member/MemberResponse.java
  src/main/java/bdbe/bdbd/member/MemberRestController.java
  src/main/java/bdbe/bdbd/member/MemberService.java
  src/main/java/bdbe/bdbd/member/OwnerRestController.java
  src/main/java/bdbe/bdbd/member/OwnerService.java
  src/test/java/bdbe/bdbd/member/MemberRestControllerTest.java
Labels: Type: Enhancement, Priority: Medium, Status: Done, Request Review

#209 Revert "fix: 로그아웃 기능 정상 작동 하게끔 코드 수정"
  build.gradle
  src/main/java/bdbe/bdbd/BdbdApplication.java
  src/main/java/bdbe/bdbd/_core/errors/config/CacheConfig.java
  src/main/java/bdbe/bdbd/_core/errors/security/CacheService.java
  src/main/java/bdbe/bdbd/_core/errors/security/JWTProvider.java
  src/main/java/bdbe/bdbd/_core/errors/security/JwtAuthenticationFilter.java
  src/main/java/bdbe/bdbd/_core/errors/security/ScheduledTasks.java
  src/main/java/bdbe/bdbd/_core/errors/security/SecurityConfig.java
  src/main/java/bdbe/bdbd/member/MemberResponse.java
  src/main/java/bdbe/bdbd/member/MemberRestController.java
  src/main/java/bdbe/bdbd/member/MemberService.java
  src/main/java/bdbe/bdbd/member/OwnerRestController.java
  src/main/java/bdbe/bdbd/member/OwnerService.java
  src/test/java/bdbe/bdbd/member/MemberRestControllerTest.java
Labels: Priority: High

#210 feat: CORS 오류를 해결하기 위해 결제리다이렉트를 서버에서 보내기
  src/main/java/bdbe/bdbd/pay/PayController.java
Labels: Priority: High

#211 refactor: DTO 유효성 검증 강화 및 에러 메세지 일관성 개선
  src/main/java/bdbe/bdbd/bay/BayRequest.java
  src/main/java/bdbe/bdbd/carwash/CarwashRequest.java
  src/main/java/bdbe/bdbd/carwash/CarwashRestController.java
  src/main/java/bdbe/bdbd/file/FileRequest.java
  src/main/java/bdbe/bdbd/member/MemberRequest.java
  src/main/java/bdbe/bdbd/pay/PayController.java
  src/main/java/bdbe/bdbd/pay/PayRequest.java
  src/main/java/bdbe/bdbd/reservation/ReservationRequest.java
  src/main/java/bdbe/bdbd/reservation/ReservationRestController.java
  src/main/java/bdbe/bdbd/review/ReviewRequest.java
  src/test/java/bdbe/bdbd/member/MemberRestControllerTest.java
Labels: Type: Enhancement, Priority: Medium, Status: Done

#212 feat: 파일 썸네일 보여주기 위한 파일 메타데이터 추가
  src/main/java/bdbe/bdbd/file/S3ProxyUploadService.java
Labels: Priority: High

#213 feat: 이미지 파일만 업로드 할 수 있게끔 파일 업로드 수정
  src/main/java/bdbe/bdbd/carwash/CarwashRestController.java
  src/main/java/bdbe/bdbd/file/FileRestController.java
  src/main/java/bdbe/bdbd/file/FileService.java
  src/main/java/bdbe/bdbd/file/S3ProxyUploadService.java
  src/main/resources/application-prod.yml
Labels: Type: Enhancement, Priority: Medium, Status: Done

#214 refactor: 코드 정리 및 유효성 검증 로직 리팩토링
  src/main/java/bdbe/bdbd/bay/BayRequest.java
  src/main/java/bdbe/bdbd/carwash/CarwashRequest.java
  src/main/java/bdbe/bdbd/file/FileRequest.java
  src/main/java/bdbe/bdbd/member/MemberRequest.java
  src/main/java/bdbe/bdbd/pay/PayRequest.java
  src/main/java/bdbe/bdbd/pay/PayResponse.java
  src/main/java/bdbe/bdbd/reservation/ReservationRequest.java
  src/main/java/bdbe/bdbd/review/ReviewRequest.java
Labels: Type: Enhancement, Priority: Low, Status: Done

#218 refactor: 패키지 분리
  src/main/java/bdbe/bdbd/controller/open/OpenCarwashController.java
  src/main/java/bdbe/bdbd/controller/open/OpenReservationController.java
  src/main/java/bdbe/bdbd/controller/open/OpenReviewController.java
  src/main/java/bdbe/bdbd/controller/owner/OwnerCarwashController.java
  src/main/java/bdbe/bdbd/controller/user/UserReviewController.java
Labels: Priority: High

#219 merge: from weekly to develop
  src/main/java/bdbe/bdbd/controller/open/OpenCarwashController.java
  src/main/java/bdbe/bdbd/controller/open/OpenReservationController.java
  src/main/java/bdbe/bdbd/controller/open/OpenReviewController.java
  src/main/java/bdbe/bdbd/controller/owner/OwnerCarwashController.java
  src/main/java/bdbe/bdbd/controller/user/UserReviewController.java
Labels: Priority: High

#220 merge: from develop to main
  src/main/java/bdbe/bdbd/controller/open/OpenCarwashController.java
  src/main/java/bdbe/bdbd/controller/open/OpenReservationController.java
  src/main/java/bdbe/bdbd/controller/open/OpenReviewController.java
  src/main/java/bdbe/bdbd/controller/owner/OwnerCarwashController.java
  src/main/java/bdbe/bdbd/controller/user/UserReviewController.java
Labels: Priority: High

#221 feat: 프론트 요구사항 반영 및 예외처리
  src/main/java/bdbe/bdbd/_core/handler/GlobalExceptionHandler.java
  src/main/java/bdbe/bdbd/_core/handler/GlobalValidationHandler.java
  src/main/java/bdbe/bdbd/controller/user/PayController.java
  src/main/java/bdbe/bdbd/controller/user/UserReservationController.java
  src/main/java/bdbe/bdbd/dto/carwash/CarwashRequest.java
  src/main/java/bdbe/bdbd/dto/member/user/UserRequest.java
  src/main/java/bdbe/bdbd/dto/pay/PayRequest.java
  src/main/java/bdbe/bdbd/dto/reservation/ReservationRequest.java
  src/main/java/bdbe/bdbd/service/carwash/CarwashService.java
  src/main/java/bdbe/bdbd/service/pay/PayService.java
  src/main/java/bdbe/bdbd/service/review/ReviewService.java
Labels: Priority: High

#222 merge: from weekly to develop (배포)
  src/main/java/bdbe/bdbd/_core/handler/GlobalExceptionHandler.java
  src/main/java/bdbe/bdbd/_core/handler/GlobalValidationHandler.java
  src/main/java/bdbe/bdbd/controller/user/PayController.java
  src/main/java/bdbe/bdbd/controller/user/UserReservationController.java
  src/main/java/bdbe/bdbd/dto/carwash/CarwashRequest.java
  src/main/java/bdbe/bdbd/dto/member/user/UserRequest.java
  src/main/java/bdbe/bdbd/dto/pay/PayRequest.java
  src/main/java/bdbe/bdbd/dto/reservation/ReservationRequest.java
  src/main/java/bdbe/bdbd/service/carwash/CarwashService.java
  src/main/java/bdbe/bdbd/service/pay/PayService.java
  src/main/java/bdbe/bdbd/service/review/ReviewService.java
Labels: Priority: High

#223 merge: from develop to main
  src/main/java/bdbe/bdbd/_core/handler/GlobalExceptionHandler.java
  src/main/java/bdbe/bdbd/_core/handler/GlobalValidationHandler.java
  src/main/java/bdbe/bdbd/controller/user/PayController.java
  src/main/java/bdbe/bdbd/controller/user/UserReservationController.java
  src/main/java/bdbe/bdbd/dto/carwash/CarwashRequest.java
  src/main/java/bdbe/bdbd/dto/member/user/UserRequest.java
  src/main/java/bdbe/bdbd/dto/pay/PayRequest.java
  src/main/java/bdbe/bdbd/dto/reservation/ReservationRequest.java
  src/main/java/bdbe/bdbd/service/carwash/CarwashService.java
  src/main/java/bdbe/bdbd/service/pay/PayService.java
  src/main/java/bdbe/bdbd/service/review/ReviewService.java
Labels: Priority: High

#224 fix: 배포 주소 변경에 따른 url변경
  src/main/resources/application-prod.yml
Labels: Type: Enhancement, Priority: Medium, Status: Done

#225 merge: from weekly to develop (배포)
  src/main/resources/application-prod.yml
Labels: Priority: High

#226 merge: from develop to main
  src/main/resources/application-prod.yml
Labels: Priority: High

#227 feat: 에러코드 정의서 반영을 위한 익셉션 구조 수정 및 기존 코드 수정
  src/main/java/bdbe/bdbd/_core/exception/ApiException.java
  src/main/java/bdbe/bdbd/_core/exception/BadGatewayError.java
  src/main/java/bdbe/bdbd/_core/exception/BadRequestError.java
  src/main/java/bdbe/bdbd/_core/exception/ForbiddenError.java
  src/main/java/bdbe/bdbd/_core/exception/InternalServerError.java
  src/main/java/bdbe/bdbd/_core/exception/NotFoundError.java
  src/main/java/bdbe/bdbd/_core/exception/UnAuthorizedError.java
  src/main/java/bdbe/bdbd/_core/handler/GlobalExceptionHandler.java
  src/main/java/bdbe/bdbd/_core/handler/GlobalValidationHandler.java
  src/main/java/bdbe/bdbd/_core/security/SecurityConfig.java
  src/main/java/bdbe/bdbd/_core/utils/ApiUtils.java
  src/main/java/bdbe/bdbd/_core/utils/FileUploadUtil.java
  src/main/java/bdbe/bdbd/_core/utils/FilterResponseUtils.java
  src/main/java/bdbe/bdbd/controller/common/CommonMemberController.java
  src/main/java/bdbe/bdbd/controller/open/OpenCarwashController.java
  src/main/java/bdbe/bdbd/controller/open/OpenMemberController.java
  src/main/java/bdbe/bdbd/model/Code.java
  src/main/java/bdbe/bdbd/model/location/Location.java
  src/main/java/bdbe/bdbd/service/bay/BayService.java
  src/main/java/bdbe/bdbd/service/carwash/CarwashService.java
  src/main/java/bdbe/bdbd/service/file/FileService.java
  src/main/java/bdbe/bdbd/service/member/OwnerService.java
  src/main/java/bdbe/bdbd/service/member/UserService.java
  src/main/java/bdbe/bdbd/service/pay/PayService.java
  src/main/java/bdbe/bdbd/service/reservation/ReservationService.java
Labels: Type: Enhancement, Priority: Medium, Status: Done

#228 refactor: DTO 검증 로직 향상 및 리팩토링
  src/main/java/bdbe/bdbd/_core/config/SwaggerConfig.java
  src/main/java/bdbe/bdbd/_core/exception/CustomErrorAttributes.java
  src/main/java/bdbe/bdbd/_core/handler/GlobalExceptionHandler.java
  src/main/java/bdbe/bdbd/_core/security/SecurityConfig.java
  src/main/java/bdbe/bdbd/controller/open/OpenCarwashController.java
  src/main/java/bdbe/bdbd/controller/owner/OwnerCarwashController.java
  src/main/java/bdbe/bdbd/controller/user/UserReviewController.java
  src/main/java/bdbe/bdbd/dto/carwash/CarwashRequest.java
  src/main/java/bdbe/bdbd/dto/carwash/CarwashResponse.java
  src/main/java/bdbe/bdbd/dto/member/owner/OwnerResponse.java
  src/main/java/bdbe/bdbd/dto/member/user/UserRequest.java
  src/main/java/bdbe/bdbd/dto/review/ReviewRequest.java
  src/main/java/bdbe/bdbd/model/location/Location.java
  src/main/java/bdbe/bdbd/service/carwash/CarwashService.java
  src/main/java/bdbe/bdbd/service/member/OwnerService.java
  src/main/java/bdbe/bdbd/service/pay/PayService.java
  src/main/java/bdbe/bdbd/service/review/ReviewService.java
  src/main/resources/application.yml
Labels: Priority: High

#229 merge: from weekly to develop (배포)
  src/main/java/bdbe/bdbd/_core/config/SwaggerConfig.java
  src/main/java/bdbe/bdbd/_core/exception/ApiException.java
  src/main/java/bdbe/bdbd/_core/exception/BadGatewayError.java
  src/main/java/bdbe/bdbd/_core/exception/BadRequestError.java
  src/main/java/bdbe/bdbd/_core/exception/CustomErrorAttributes.java
  src/main/java/bdbe/bdbd/_core/exception/ForbiddenError.java
  src/main/java/bdbe/bdbd/_core/exception/InternalServerError.java
  src/main/java/bdbe/bdbd/_core/exception/NotFoundError.java
  src/main/java/bdbe/bdbd/_core/exception/UnAuthorizedError.java
  src/main/java/bdbe/bdbd/_core/handler/GlobalExceptionHandler.java
  src/main/java/bdbe/bdbd/_core/handler/GlobalValidationHandler.java
  src/main/java/bdbe/bdbd/_core/security/SecurityConfig.java
  src/main/java/bdbe/bdbd/_core/utils/ApiUtils.java
  src/main/java/bdbe/bdbd/_core/utils/FileUploadUtil.java
  src/main/java/bdbe/bdbd/_core/utils/FilterResponseUtils.java
  src/main/java/bdbe/bdbd/controller/common/CommonMemberController.java
  src/main/java/bdbe/bdbd/controller/open/OpenCarwashController.java
  src/main/java/bdbe/bdbd/controller/open/OpenMemberController.java
  src/main/java/bdbe/bdbd/controller/owner/OwnerCarwashController.java
  src/main/java/bdbe/bdbd/controller/user/UserReviewController.java
  src/main/java/bdbe/bdbd/dto/carwash/CarwashRequest.java
  src/main/java/bdbe/bdbd/dto/carwash/CarwashResponse.java
  src/main/java/bdbe/bdbd/dto/member/owner/OwnerResponse.java
  src/main/java/bdbe/bdbd/dto/member/user/UserRequest.java
  src/main/java/bdbe/bdbd/dto/review/ReviewRequest.java
  src/main/java/bdbe/bdbd/model/Code.java
  src/main/java/bdbe/bdbd/model/location/Location.java
  src/main/java/bdbe/bdbd/service/bay/BayService.java
  src/main/java/bdbe/bdbd/service/carwash/CarwashService.java
  src/main/java/bdbe/bdbd/service/file/FileService.java
  src/main/java/bdbe/bdbd/service/member/OwnerService.java
  src/main/java/bdbe/bdbd/service/member/UserService.java
  src/main/java/bdbe/bdbd/service/pay/PayService.java
  src/main/java/bdbe/bdbd/service/reservation/ReservationService.java
  src/main/java/bdbe/bdbd/service/review/ReviewService.java
  src/main/resources/application.yml
Labels: Priority: High

#230 merge: from develop to main
  src/main/java/bdbe/bdbd/_core/config/SwaggerConfig.java
  src/main/java/bdbe/bdbd/_core/exception/ApiException.java
  src/main/java/bdbe/bdbd/_core/exception/BadGatewayError.java
  src/main/java/bdbe/bdbd/_core/exception/BadRequestError.java
  src/main/java/bdbe/bdbd/_core/exception/CustomErrorAttributes.java
  src/main/java/bdbe/bdbd/_core/exception/ForbiddenError.java
  src/main/java/bdbe/bdbd/_core/exception/InternalServerError.java
  src/main/java/bdbe/bdbd/_core/exception/NotFoundError.java
  src/main/java/bdbe/bdbd/_core/exception/UnAuthorizedError.java
  src/main/java/bdbe/bdbd/_core/handler/GlobalExceptionHandler.java
  src/main/java/bdbe/bdbd/_core/handler/GlobalValidationHandler.java
  src/main/java/bdbe/bdbd/_core/security/SecurityConfig.java
  src/main/java/bdbe/bdbd/_core/utils/ApiUtils.java
  src/main/java/bdbe/bdbd/_core/utils/FileUploadUtil.java
  src/main/java/bdbe/bdbd/_core/utils/FilterResponseUtils.java
  src/main/java/bdbe/bdbd/controller/common/CommonMemberController.java
  src/main/java/bdbe/bdbd/controller/open/OpenCarwashController.java
  src/main/java/bdbe/bdbd/controller/open/OpenMemberController.java
  src/main/java/bdbe/bdbd/controller/owner/OwnerCarwashController.java
  src/main/java/bdbe/bdbd/controller/user/UserReviewController.java
  src/main/java/bdbe/bdbd/dto/carwash/CarwashRequest.java
  src/main/java/bdbe/bdbd/dto/carwash/CarwashResponse.java
  src/main/java/bdbe/bdbd/dto/member/owner/OwnerResponse.java
  src/main/java/bdbe/bdbd/dto/member/user/UserRequest.java
  src/main/java/bdbe/bdbd/dto/review/ReviewRequest.java
  src/main/java/bdbe/bdbd/model/Code.java
  src/main/java/bdbe/bdbd/model/location/Location.java
  src/main/java/bdbe/bdbd/service/bay/BayService.java
  src/main/java/bdbe/bdbd/service/carwash/CarwashService.java
  src/main/java/bdbe/bdbd/service/file/FileService.java
  src/main/java/bdbe/bdbd/service/member/OwnerService.java
  src/main/java/bdbe/bdbd/service/member/UserService.java
  src/main/java/bdbe/bdbd/service/pay/PayService.java
  src/main/java/bdbe/bdbd/service/reservation/ReservationService.java
  src/main/java/bdbe/bdbd/service/review/ReviewService.java
  src/main/resources/application.yml
Labels: Priority: High

#231 delete: 필요없는 코드 삭제
  src/main/java/bdbe/bdbd/dto/bay/BayRequest.java
  src/main/java/bdbe/bdbd/dto/carwash/CarwashRequest.java
  src/test/java/bdbe/bdbd/carwash/CarwashRestControllerTest.java
Labels: Priority: High

#232 merge: from weekly to develop (배포)
  src/main/java/bdbe/bdbd/dto/bay/BayRequest.java
  src/main/java/bdbe/bdbd/dto/carwash/CarwashRequest.java
  src/test/java/bdbe/bdbd/carwash/CarwashRestControllerTest.java
Labels: Priority: High

#233 merge: from develop to main
  src/main/java/bdbe/bdbd/dto/bay/BayRequest.java
  src/main/java/bdbe/bdbd/dto/carwash/CarwashRequest.java
  src/test/java/bdbe/bdbd/carwash/CarwashRestControllerTest.java
Labels: Priority: High

#234 feat: 변경사항 적용
  src/main/java/bdbe/bdbd/controller/owner/OwnerCarwashController.java
  src/main/java/bdbe/bdbd/dto/carwash/CarwashRequest.java
  src/main/java/bdbe/bdbd/service/carwash/CarwashService.java
Labels: Priority: Urgent

#237 feat: 세차장 관련 기능 개선 및 예외 처리 추가
  src/main/java/bdbe/bdbd/controller/owner/OwnerCarwashController.java
  src/main/java/bdbe/bdbd/dto/carwash/CarwashRequest.java
  src/main/java/bdbe/bdbd/service/carwash/CarwashService.java
  src/main/java/bdbe/bdbd/service/reservation/ReservationService.java
Labels: Priority: High

#238 merge: from weekly to develop
  src/main/java/bdbe/bdbd/controller/owner/OwnerCarwashController.java
  src/main/java/bdbe/bdbd/dto/carwash/CarwashRequest.java
  src/main/java/bdbe/bdbd/service/carwash/CarwashService.java
  src/main/java/bdbe/bdbd/service/reservation/ReservationService.java
Labels: Priority: High

#239 merge: from develop to main (배포)
  src/main/java/bdbe/bdbd/controller/owner/OwnerCarwashController.java
  src/main/java/bdbe/bdbd/dto/carwash/CarwashRequest.java
  src/main/java/bdbe/bdbd/service/carwash/CarwashService.java
  src/main/java/bdbe/bdbd/service/reservation/ReservationService.java
Labels: Priority: High

#240 fix: 클라이언트에게 명확한 에러 메시지와 적절한 에러 코드 제공
  src/main/java/bdbe/bdbd/_core/exception/ApiException.java
  src/main/java/bdbe/bdbd/_core/exception/BadGatewayError.java
  src/main/java/bdbe/bdbd/_core/exception/BadRequestError.java
  src/main/java/bdbe/bdbd/_core/exception/ForbiddenError.java
  src/main/java/bdbe/bdbd/_core/exception/InternalServerError.java
  src/main/java/bdbe/bdbd/_core/exception/NotFoundError.java
  src/main/java/bdbe/bdbd/_core/exception/UnAuthorizedError.java
  src/main/java/bdbe/bdbd/_core/handler/GlobalValidationHandler.java
  src/main/java/bdbe/bdbd/_core/security/SecurityConfig.java
  src/main/java/bdbe/bdbd/_core/utils/ApiUtils.java
  src/main/java/bdbe/bdbd/_core/utils/FilterResponseUtils.java
  src/main/java/bdbe/bdbd/model/bay/Bay.java
  src/main/java/bdbe/bdbd/service/bay/BayService.java
  src/main/java/bdbe/bdbd/service/carwash/CarwashService.java
  src/main/java/bdbe/bdbd/service/file/FileService.java
  src/main/java/bdbe/bdbd/service/member/OwnerService.java
  src/main/java/bdbe/bdbd/service/member/UserService.java
  src/main/java/bdbe/bdbd/service/pay/PayService.java
  src/main/java/bdbe/bdbd/service/reservation/ReservationService.java
  src/main/java/bdbe/bdbd/service/review/ReviewService.java
  src/test/java/bdbe/bdbd/reservation/ReservationRestControllerTest.java
  src/test/java/bdbe/bdbd/review/ReviewRestControllerTest.java
Labels: Type: Enhancement, Priority: Medium, Status: Done

#241 fix: 메시지 json 형식 정상 반환 및 ApiException관련 없이 답변 일관성 추가
  src/main/java/bdbe/bdbd/_core/exception/BadGatewayError.java
  src/main/java/bdbe/bdbd/_core/exception/BadRequestError.java
  src/main/java/bdbe/bdbd/_core/exception/ForbiddenError.java
  src/main/java/bdbe/bdbd/_core/exception/InternalServerError.java
  src/main/java/bdbe/bdbd/_core/exception/NotFoundError.java
  src/main/java/bdbe/bdbd/_core/exception/UnAuthorizedError.java
  src/main/java/bdbe/bdbd/_core/handler/GlobalExceptionHandler.java
  src/main/java/bdbe/bdbd/_core/utils/ApiUtils.java
Labels: Type: Enhancement, Priority: Medium, Status: Done

#242 Weekly
  src/main/java/bdbe/bdbd/_core/exception/CustomErrorAttributes.java
  src/main/java/bdbe/bdbd/_core/utils/DownloadUtils.java
  src/main/java/bdbe/bdbd/_core/utils/FileUploadUtil.java
  src/main/java/bdbe/bdbd/service/carwash/CarwashService.java
  src/main/java/bdbe/bdbd/service/file/FileService.java
  src/main/java/bdbe/bdbd/service/file/S3ProxyUploadService.java
  src/main/java/bdbe/bdbd/service/member/OwnerService.java
  src/main/resources/application-prod.yml
Labels: Type: Bug, Type: Enhancement, Priority: High, Status: Done

#243 merge: from weekly to develop
  src/main/java/bdbe/bdbd/_core/exception/ApiException.java
  src/main/java/bdbe/bdbd/_core/exception/BadGatewayError.java
  src/main/java/bdbe/bdbd/_core/exception/BadRequestError.java
  src/main/java/bdbe/bdbd/_core/exception/CustomErrorAttributes.java
  src/main/java/bdbe/bdbd/_core/exception/ForbiddenError.java
  src/main/java/bdbe/bdbd/_core/exception/InternalServerError.java
  src/main/java/bdbe/bdbd/_core/exception/NotFoundError.java
  src/main/java/bdbe/bdbd/_core/exception/UnAuthorizedError.java
  src/main/java/bdbe/bdbd/_core/handler/GlobalExceptionHandler.java
  src/main/java/bdbe/bdbd/_core/handler/GlobalValidationHandler.java
  src/main/java/bdbe/bdbd/_core/security/SecurityConfig.java
  src/main/java/bdbe/bdbd/_core/utils/ApiUtils.java
  src/main/java/bdbe/bdbd/_core/utils/DownloadUtils.java
  src/main/java/bdbe/bdbd/_core/utils/FileUploadUtil.java
  src/main/java/bdbe/bdbd/_core/utils/FilterResponseUtils.java
  src/main/java/bdbe/bdbd/model/bay/Bay.java
  src/main/java/bdbe/bdbd/service/bay/BayService.java
  src/main/java/bdbe/bdbd/service/carwash/CarwashService.java
  src/main/java/bdbe/bdbd/service/file/FileService.java
  src/main/java/bdbe/bdbd/service/file/S3ProxyUploadService.java
  src/main/java/bdbe/bdbd/service/member/OwnerService.java
  src/main/java/bdbe/bdbd/service/member/UserService.java
  src/main/java/bdbe/bdbd/service/pay/PayService.java
  src/main/java/bdbe/bdbd/service/reservation/ReservationService.java
  src/main/java/bdbe/bdbd/service/review/ReviewService.java
  src/main/resources/application-prod.yml
  src/test/java/bdbe/bdbd/reservation/ReservationRestControllerTest.java
  src/test/java/bdbe/bdbd/review/ReviewRestControllerTest.java
Labels: Priority: High

#244 merge: from develop to main (배포)
  src/main/java/bdbe/bdbd/_core/exception/ApiException.java
  src/main/java/bdbe/bdbd/_core/exception/BadGatewayError.java
  src/main/java/bdbe/bdbd/_core/exception/BadRequestError.java
  src/main/java/bdbe/bdbd/_core/exception/CustomErrorAttributes.java
  src/main/java/bdbe/bdbd/_core/exception/ForbiddenError.java
  src/main/java/bdbe/bdbd/_core/exception/InternalServerError.java
  src/main/java/bdbe/bdbd/_core/exception/NotFoundError.java
  src/main/java/bdbe/bdbd/_core/exception/UnAuthorizedError.java
  src/main/java/bdbe/bdbd/_core/handler/GlobalExceptionHandler.java
  src/main/java/bdbe/bdbd/_core/handler/GlobalValidationHandler.java
  src/main/java/bdbe/bdbd/_core/security/SecurityConfig.java
  src/main/java/bdbe/bdbd/_core/utils/ApiUtils.java
  src/main/java/bdbe/bdbd/_core/utils/DownloadUtils.java
  src/main/java/bdbe/bdbd/_core/utils/FileUploadUtil.java
  src/main/java/bdbe/bdbd/_core/utils/FilterResponseUtils.java
  src/main/java/bdbe/bdbd/model/bay/Bay.java
  src/main/java/bdbe/bdbd/service/bay/BayService.java
  src/main/java/bdbe/bdbd/service/carwash/CarwashService.java
  src/main/java/bdbe/bdbd/service/file/FileService.java
  src/main/java/bdbe/bdbd/service/file/S3ProxyUploadService.java
  src/main/java/bdbe/bdbd/service/member/OwnerService.java
  src/main/java/bdbe/bdbd/service/member/UserService.java
  src/main/java/bdbe/bdbd/service/pay/PayService.java
  src/main/java/bdbe/bdbd/service/reservation/ReservationService.java
  src/main/java/bdbe/bdbd/service/review/ReviewService.java
  src/main/resources/application-prod.yml
  src/test/java/bdbe/bdbd/reservation/ReservationRestControllerTest.java
  src/test/java/bdbe/bdbd/review/ReviewRestControllerTest.java
Labels: Priority: High

#245 fix: 이메일 중복 에러 반환 정상화
  src/main/java/bdbe/bdbd/controller/open/OpenMemberController.java
  src/main/java/bdbe/bdbd/service/member/UserService.java
Labels: Type: Enhancement, Priority: Medium, Status: Done

#250 fix: 세차장 검색 기능 합집합에서 교집합으로 수정
  src/main/java/bdbe/bdbd/service/carwash/CarwashService.java
Labels: Type: Bug, Priority: Medium, Status: Done

#251 refactor: tel 검증코드 수정
  src/main/java/bdbe/bdbd/controller/owner/OwnerBayRestController.java
  src/main/java/bdbe/bdbd/dto/bay/BayResponse.java
  src/main/java/bdbe/bdbd/dto/carwash/CarwashRequest.java
  src/main/java/bdbe/bdbd/dto/member/owner/OwnerResponse.java
  src/main/java/bdbe/bdbd/dto/member/user/UserRequest.java
  src/main/java/bdbe/bdbd/repository/reservation/ReservationJPARepository.java
  src/main/java/bdbe/bdbd/service/bay/BayService.java
  src/main/java/bdbe/bdbd/service/member/OwnerService.java
Labels: Priority: High

#253 merge: from weekly to develop
  src/main/java/bdbe/bdbd/_core/security/SecurityConfig.java
  src/main/java/bdbe/bdbd/controller/owner/OwnerBayRestController.java
  src/main/java/bdbe/bdbd/dto/bay/BayResponse.java
  src/main/java/bdbe/bdbd/dto/carwash/CarwashRequest.java
  src/main/java/bdbe/bdbd/dto/member/owner/OwnerResponse.java
  src/main/java/bdbe/bdbd/dto/member/user/UserRequest.java
  src/main/java/bdbe/bdbd/repository/reservation/ReservationJPARepository.java
  src/main/java/bdbe/bdbd/service/bay/BayService.java
  src/main/java/bdbe/bdbd/service/carwash/CarwashService.java
  src/main/java/bdbe/bdbd/service/member/OwnerService.java
  src/main/resources/application-prod.yml
Labels: Priority: High

#254 merge: from develop to main
  src/main/java/bdbe/bdbd/_core/security/SecurityConfig.java
  src/main/java/bdbe/bdbd/controller/owner/OwnerBayRestController.java
  src/main/java/bdbe/bdbd/dto/bay/BayResponse.java
  src/main/java/bdbe/bdbd/dto/carwash/CarwashRequest.java
  src/main/java/bdbe/bdbd/dto/member/owner/OwnerResponse.java
  src/main/java/bdbe/bdbd/dto/member/user/UserRequest.java
  src/main/java/bdbe/bdbd/repository/reservation/ReservationJPARepository.java
  src/main/java/bdbe/bdbd/service/bay/BayService.java
  src/main/java/bdbe/bdbd/service/carwash/CarwashService.java
  src/main/java/bdbe/bdbd/service/member/OwnerService.java
  src/main/resources/application-prod.yml
Labels: Priority: High

#255 refactor: 예약 목록 조회 url 변경
  src/main/java/bdbe/bdbd/controller/owner/OwnerCarwashController.java
Labels: Priority: High

#256 merge: from weekly to develop
  src/main/java/bdbe/bdbd/controller/owner/OwnerCarwashController.java
Labels: Priority: High

#257 merge: from develop to main
  src/main/java/bdbe/bdbd/controller/owner/OwnerCarwashController.java
Labels: Priority: High

#259 fix: 매출관리 버그 수정
  src/main/java/bdbe/bdbd/repository/reservation/ReservationJPARepository.java
  src/main/java/bdbe/bdbd/service/member/OwnerService.java
Labels: Priority: High

#260 merge: from weekly to develop
  src/main/java/bdbe/bdbd/repository/reservation/ReservationJPARepository.java
  src/main/java/bdbe/bdbd/service/member/OwnerService.java
Labels: Priority: High

#261 merge: from develop to main
  src/main/java/bdbe/bdbd/repository/reservation/ReservationJPARepository.java
  src/main/java/bdbe/bdbd/service/member/OwnerService.java
Labels: Priority: Medium

#263 refactor: 프론트 요구사항 반영 및 버그 해결
  src/main/java/bdbe/bdbd/controller/owner/OwnerCarwashController.java
  src/main/java/bdbe/bdbd/repository/reservation/ReservationJPARepository.java
  src/main/java/bdbe/bdbd/service/bay/BayService.java
  src/main/java/bdbe/bdbd/service/member/OwnerService.java
Labels: Priority: Urgent

#264 merge: from weekly to develop
  src/main/java/bdbe/bdbd/_core/security/JwtAuthenticationFilter.java
  src/main/java/bdbe/bdbd/controller/owner/OwnerCarwashController.java
  src/main/java/bdbe/bdbd/repository/reservation/ReservationJPARepository.java
  src/main/java/bdbe/bdbd/service/bay/BayService.java
  src/main/java/bdbe/bdbd/service/carwash/CarwashService.java
  src/main/java/bdbe/bdbd/service/member/OwnerService.java
  src/test/java/bdbe/bdbd/bay/BayRestControllerTest.java
  src/test/java/bdbe/bdbd/carwash/CarwashRestControllerTest.java
  src/test/java/bdbe/bdbd/member/owner/OwnerRestControllerTest.java
  src/test/java/bdbe/bdbd/member/user/UserRestControllerTest.java
  src/test/java/bdbe/bdbd/pay/PayRestControllerTest.java
  src/test/java/bdbe/bdbd/reservation/ReservationRestControllerTest.java
  src/test/java/bdbe/bdbd/review/ReviewRestControllerTest.java
Labels: Priority: High

#265 merge: form develop to main
  src/main/java/bdbe/bdbd/_core/security/JwtAuthenticationFilter.java
  src/main/java/bdbe/bdbd/controller/owner/OwnerCarwashController.java
  src/main/java/bdbe/bdbd/repository/reservation/ReservationJPARepository.java
  src/main/java/bdbe/bdbd/service/bay/BayService.java
  src/main/java/bdbe/bdbd/service/carwash/CarwashService.java
  src/main/java/bdbe/bdbd/service/member/OwnerService.java
  src/test/java/bdbe/bdbd/bay/BayRestControllerTest.java
  src/test/java/bdbe/bdbd/carwash/CarwashRestControllerTest.java
  src/test/java/bdbe/bdbd/member/owner/OwnerRestControllerTest.java
  src/test/java/bdbe/bdbd/member/user/UserRestControllerTest.java
  src/test/java/bdbe/bdbd/pay/PayRestControllerTest.java
  src/test/java/bdbe/bdbd/reservation/ReservationRestControllerTest.java
  src/test/java/bdbe/bdbd/review/ReviewRestControllerTest.java
Labels: Priority: High

#267 feat: 코드 추가 및 개선
  src/main/java/bdbe/bdbd/controller/open/OpenCarwashController.java
  src/main/java/bdbe/bdbd/controller/owner/OwnerBayRestController.java
  src/main/java/bdbe/bdbd/controller/owner/OwnerCarwashController.java
  src/main/java/bdbe/bdbd/controller/user/UserPayController.java
  src/main/java/bdbe/bdbd/controller/user/UserReservationController.java
  src/main/java/bdbe/bdbd/controller/user/UserReviewController.java
  src/main/java/bdbe/bdbd/dto/pay/PayRequest.java
  src/main/java/bdbe/bdbd/dto/reservation/ReservationRequest.java
  src/main/java/bdbe/bdbd/service/bay/BayService.java
  src/main/java/bdbe/bdbd/service/pay/PayService.java
  src/main/java/bdbe/bdbd/service/reservation/ReservationService.java
  src/main/resources/application-prod.yml
Labels: Priority: High

#268 merge: from weekly to develop
  src/main/java/bdbe/bdbd/_core/security/JwtAuthenticationFilter.java
  src/main/java/bdbe/bdbd/_core/utils/ApiUtils.java
  src/main/java/bdbe/bdbd/_core/utils/MemberUtils.java
  src/main/java/bdbe/bdbd/controller/open/OpenCarwashController.java
  src/main/java/bdbe/bdbd/controller/open/OpenMemberController.java
  src/main/java/bdbe/bdbd/controller/owner/OwnerBayRestController.java
  src/main/java/bdbe/bdbd/controller/owner/OwnerCarwashController.java
  src/main/java/bdbe/bdbd/controller/user/UserPayController.java
  src/main/java/bdbe/bdbd/controller/user/UserReservationController.java
  src/main/java/bdbe/bdbd/controller/user/UserReviewController.java
  src/main/java/bdbe/bdbd/dto/pay/PayRequest.java
  src/main/java/bdbe/bdbd/dto/reservation/ReservationRequest.java
  src/main/java/bdbe/bdbd/service/bay/BayService.java
  src/main/java/bdbe/bdbd/service/member/OwnerService.java
  src/main/java/bdbe/bdbd/service/member/UserService.java
  src/main/java/bdbe/bdbd/service/pay/PayService.java
  src/main/java/bdbe/bdbd/service/reservation/ReservationService.java
  src/main/resources/application-prod.yml
Labels: Priority: High

#269 merge: from develop to main
  src/main/java/bdbe/bdbd/_core/security/JwtAuthenticationFilter.java
  src/main/java/bdbe/bdbd/_core/utils/ApiUtils.java
  src/main/java/bdbe/bdbd/_core/utils/MemberUtils.java
  src/main/java/bdbe/bdbd/controller/open/OpenCarwashController.java
  src/main/java/bdbe/bdbd/controller/open/OpenMemberController.java
  src/main/java/bdbe/bdbd/controller/owner/OwnerBayRestController.java
  src/main/java/bdbe/bdbd/controller/owner/OwnerCarwashController.java
  src/main/java/bdbe/bdbd/controller/user/UserPayController.java
  src/main/java/bdbe/bdbd/controller/user/UserReservationController.java
  src/main/java/bdbe/bdbd/controller/user/UserReviewController.java
  src/main/java/bdbe/bdbd/dto/pay/PayRequest.java
  src/main/java/bdbe/bdbd/dto/reservation/ReservationRequest.java
  src/main/java/bdbe/bdbd/service/bay/BayService.java
  src/main/java/bdbe/bdbd/service/member/OwnerService.java
  src/main/java/bdbe/bdbd/service/member/UserService.java
  src/main/java/bdbe/bdbd/service/pay/PayService.java
  src/main/java/bdbe/bdbd/service/reservation/ReservationService.java
  src/main/resources/application-prod.yml
Labels: Priority: High

#271 merge: from weekly to develop
  src/main/java/bdbe/bdbd/dto/carwash/CarwashRequest.java
  src/main/java/bdbe/bdbd/service/carwash/CarwashService.java
  src/test/java/bdbe/bdbd/carwash/CarwashRestControllerTest.java
Labels: Priority: High

#272 merge: from develop to main
  src/main/java/bdbe/bdbd/dto/carwash/CarwashRequest.java
  src/main/java/bdbe/bdbd/service/carwash/CarwashService.java
  src/test/java/bdbe/bdbd/carwash/CarwashRestControllerTest.java
Labels: Priority: High

#273 delete: 필요 없는 코드 삭제
  src/main/java/bdbe/bdbd/controller/user/UserReservationController.java
  src/main/java/bdbe/bdbd/dto/pay/PayRequest.java
  src/main/java/bdbe/bdbd/dto/reservation/ReservationRequest.java
  src/main/java/bdbe/bdbd/service/reservation/ReservationService.java
Labels: Priority: High

#274 merge: from weekly to develop
  src/main/java/bdbe/bdbd/controller/user/UserReservationController.java
  src/main/java/bdbe/bdbd/dto/pay/PayRequest.java
  src/main/java/bdbe/bdbd/dto/reservation/ReservationRequest.java
  src/main/java/bdbe/bdbd/service/reservation/ReservationService.java
Labels: Priority: High

#275 merge: from develop to main
  src/main/java/bdbe/bdbd/controller/user/UserReservationController.java
  src/main/java/bdbe/bdbd/dto/pay/PayRequest.java
  src/main/java/bdbe/bdbd/dto/reservation/ReservationRequest.java
  src/main/java/bdbe/bdbd/service/reservation/ReservationService.java
Labels: Priority: High

#276 refactor: 변수명 변경
  src/main/java/bdbe/bdbd/dto/carwash/CarwashResponse.java
  src/main/java/bdbe/bdbd/service/carwash/CarwashService.java
Labels: Priority: High

#277 merge: from weekly to develop
  src/main/java/bdbe/bdbd/dto/carwash/CarwashResponse.java
  src/main/java/bdbe/bdbd/service/carwash/CarwashService.java
Labels: Priority: High

#278 merge: from develop to main
  src/main/java/bdbe/bdbd/dto/carwash/CarwashResponse.java
  src/main/java/bdbe/bdbd/service/carwash/CarwashService.java
Labels: Priority: High

#279 fix: 변수명 변경
  src/main/java/bdbe/bdbd/controller/owner/OwnerCarwashController.java
  src/main/java/bdbe/bdbd/dto/carwash/CarwashRequest.java
  src/main/java/bdbe/bdbd/service/carwash/CarwashService.java
  src/test/java/bdbe/bdbd/carwash/CarwashRestControllerTest.java
Labels: Priority: High

#281 fix: 변수명 변경
  src/main/java/bdbe/bdbd/controller/owner/OwnerCarwashController.java
  src/main/java/bdbe/bdbd/dto/carwash/CarwashRequest.java
  src/main/java/bdbe/bdbd/service/carwash/CarwashService.java
  src/test/java/bdbe/bdbd/carwash/CarwashRestControllerTest.java
Labels: Priority: High

#285 fix: 버그 수정
  README.md
  readme_images/Untitled 1.png
  readme_images/Untitled 2.png
  readme_images/Untitled 3.png
  readme_images/Untitled 4.png
  readme_images/Untitled 5.png
  readme_images/Untitled.png
  src/main/java/bdbe/bdbd/repository/bay/BayJPARepository.java
  src/main/java/bdbe/bdbd/service/bay/BayService.java
  src/main/java/bdbe/bdbd/service/carwash/CarwashService.java
  src/main/java/bdbe/bdbd/service/member/OwnerService.java
  src/main/java/bdbe/bdbd/service/reservation/ReservationService.java
  src/test/java/bdbe/bdbd/reservation/ReservationRestControllerTest.java
Labels: Priority: High

#286 fix: 버그 수정
  src/main/java/bdbe/bdbd/repository/bay/BayJPARepository.java
  src/main/java/bdbe/bdbd/service/bay/BayService.java
  src/main/java/bdbe/bdbd/service/member/OwnerService.java
Labels: Priority: High
