Repository Step3-kakao-tech-campus/Team10_BE, pull requests merged in 2023-10, with the labels that each got.

#14 feat: 세차장 평균 별점 계산 기능 구현
  .idea/sonarlint/issuestore/index.pb
  .idea/sonarlint/securityhotspotstore/index.pb
  .idea/workspace.xml
  src/main/java/bdbe/bdbd/carwash/Carwash.java
  src/main/java/bdbe/bdbd/carwash/CarwashResponse.java
  src/main/java/bdbe/bdbd/review/Review.java
  src/main/java/bdbe/bdbd/review/ReviewJPARepository.java
  src/main/java/bdbe/bdbd/review/ReviewRequest.java
  src/main/java/bdbe/bdbd/review/ReviewResponse.java
  src/main/java/bdbe/bdbd/review/ReviewService.java
  src/test/java/bdbe/bdbd/carwash/CarwashRestControllerTest.java
  src/test/java/bdbe/bdbd/review/ReviewRestControllerTest.java
Labels: Type: Bug, Priority: High, Status: Done

#15 delete ./idea ./gradle 디렉토리 삭제
  .gradle/8.2.1/checksums/checksums.lock
  .gradle/8.2.1/dependencies-accessors/dependencies-accessors.lock
  .gradle/8.2.1/dependencies-accessors/gc.properties
  .gradle/8.2.1/executionHistory/executionHistory.lock
  .gradle/8.2.1/fileChanges/last-build.bin
  .gradle/8.2.1/fileHashes/fileHashes.lock
  .gradle/8.2.1/gc.properties
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/cache.properties
  .gradle/vcs-1/gc.properties
Labels: Type: Enhancement, Priority: Medium, Status: Done

#16 delete .idea 디렉토리 삭제
  .idea/.name
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/modules/bdbd.iml
  .idea/modules/bdbd.main.iml
  .idea/modules/bdbd.test.iml
  .idea/sonarlint/issuestore/8/e/8ec9a00bfd09b3190ac6b22251dbb1aa95a0579d
  .idea/sonarlint/issuestore/index.pb
  .idea/sonarlint/securityhotspotstore/8/e/8ec9a00bfd09b3190ac6b22251dbb1aa95a0579d
  .idea/sonarlint/securityhotspotstore/index.pb
  .idea/vcs.xml
  .idea/workspace.xml
Labels: Type: Enhancement, Priority: Medium, Status: In Progress

#17 delete: 캐시 삭제
  build/tmp/compileJava/previous-compilation-data.bin
Labels: Type: Enhancement, Priority: Medium, Status: In Progress

#18 delete: .gradle 디렉토리 삭제
  .gradle/8.2.1/checksums/checksums.lock
  .gradle/8.2.1/dependencies-accessors/dependencies-accessors.lock
  .gradle/8.2.1/dependencies-accessors/gc.properties
  .gradle/8.2.1/executionHistory/executionHistory.lock
  .gradle/8.2.1/fileChanges/last-build.bin
  .gradle/8.2.1/fileHashes/fileHashes.lock
  .gradle/8.2.1/gc.properties
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/cache.properties
  .gradle/vcs-1/gc.properties
Labels: Type: Enhancement, Priority: Medium, Status: In Progress

#20 delete: .idea 디렉토리 삭제
  .idea/.name
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/modules/bdbd.iml
  .idea/modules/bdbd.main.iml
  .idea/modules/bdbd.test.iml
  .idea/sonarlint/issuestore/8/e/8ec9a00bfd09b3190ac6b22251dbb1aa95a0579d
  .idea/sonarlint/issuestore/index.pb
  .idea/sonarlint/securityhotspotstore/8/e/8ec9a00bfd09b3190ac6b22251dbb1aa95a0579d
  .idea/sonarlint/securityhotspotstore/index.pb
  .idea/vcs.xml
  .idea/workspace.xml
Labels: Type: Enhancement, Priority: Medium, Status: In Progress

#21 delete: .gradle 디렉토리 삭제
  .gradle/8.2.1/checksums/checksums.lock
  .gradle/8.2.1/dependencies-accessors/dependencies-accessors.lock
  .gradle/8.2.1/dependencies-accessors/gc.properties
  .gradle/8.2.1/executionHistory/executionHistory.lock
  .gradle/8.2.1/fileChanges/last-build.bin
  .gradle/8.2.1/fileHashes/fileHashes.lock
  .gradle/8.2.1/gc.properties
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/cache.properties
  .gradle/vcs-1/gc.properties
Labels: Type: Enhancement, Priority: Medium, Status: In Progress

#23 delete: .idea 디렉토리 삭제
  .idea/.name
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/modules/bdbd.iml
  .idea/modules/bdbd.main.iml
  .idea/modules/bdbd.test.iml
  .idea/sonarlint/issuestore/8/e/8ec9a00bfd09b3190ac6b22251dbb1aa95a0579d
  .idea/sonarlint/issuestore/index.pb
  .idea/sonarlint/securityhotspotstore/8/e/8ec9a00bfd09b3190ac6b22251dbb1aa95a0579d
  .idea/sonarlint/securityhotspotstore/index.pb
  .idea/vcs.xml
  .idea/workspace.xml
Labels: Type: Enhancement, Priority: Medium, Status: In Progress

#30 feat: 예약 기능 및 세차장별 예약 조회 기능 구현
  build/reports/tests/test/classes/bdbe.bdbd.reservation.ReservationRestControllerTest.html
  build/reports/tests/test/css/base-style.css
  build/reports/tests/test/css/style.css
  build/reports/tests/test/index.html
  build/reports/tests/test/js/report.js
  build/reports/tests/test/packages/bdbe.bdbd.reservation.html
  build/test-results/test/TEST-bdbe.bdbd.reservation.ReservationRestControllerTest.xml
  build/test-results/test/binary/output.bin
  build/test-results/test/binary/output.bin.idx
  build/test-results/test/binary/results.bin
  build/tmp/compileJava/compileTransaction/stash-dir/BayJPARepository.class.uniqueId1
  build/tmp/compileJava/compileTransaction/stash-dir/CustomUserDetails.class.uniqueId10
  build/tmp/compileJava/compileTransaction/stash-dir/CustomUserDetailsService.class.uniqueId7
  build/tmp/compileJava/compileTransaction/stash-dir/JWTProvider.class.uniqueId15
  build/tmp/compileJava/compileTransaction/stash-dir/JwtAuthenticationFilter.class.uniqueId6
  build/tmp/compileJava/compileTransaction/stash-dir/ReservationJPARepository.class.uniqueId11
  build/tmp/compileJava/compileTransaction/stash-dir/ReservationRequest$SaveDTO$TimeDTO.class.uniqueId0
  build/tmp/compileJava/compileTransaction/stash-dir/ReservationRequest$SaveDTO.class.uniqueId8
  build/tmp/compileJava/compileTransaction/stash-dir/ReservationRequest$findAllRequestDTO.class.uniqueId7
  build/tmp/compileJava/compileTransaction/stash-dir/ReservationRequest.class.uniqueId4
  build/tmp/compileJava/compileTransaction/stash-dir/ReservationResponse$findAllResponseDTO$BayResponseDTO.class.uniqueId9
  build/tmp/compileJava/compileTransaction/stash-dir/ReservationResponse$findAllResponseDTO$BookedTimeDTO.class.uniqueId3
  build/tmp/compileJava/compileTransaction/stash-dir/ReservationResponse$findAllResponseDTO.class.uniqueId6
  build/tmp/compileJava/compileTransaction/stash-dir/ReservationResponse.class.uniqueId10
  build/tmp/compileJava/compileTransaction/stash-dir/ReservationRestController.class.uniqueId2
  build/tmp/compileJava/compileTransaction/stash-dir/ReservationService.class.uniqueId5
  build/tmp/compileJava/compileTransaction/stash-dir/User$UserBuilder.class.uniqueId12
  build/tmp/compileJava/compileTransaction/stash-dir/User.class.uniqueId14
  build/tmp/compileJava/compileTransaction/stash-dir/UserJPARepository.class.uniqueId1
  build/tmp/compileJava/compileTransaction/stash-dir/UserRequest$EmailCheckDTO.class.uniqueId2
  build/tmp/compileJava/compileTransaction/stash-dir/UserRequest$JoinDTO.class.uniqueId9
  build/tmp/compileJava/compileTransaction/stash-dir/UserRequest$LoginDTO.class.uniqueId4
  build/tmp/compileJava/compileTransaction/stash-dir/UserRequest$UpdatePasswordDTO.class.uniqueId13
  build/tmp/compileJava/compileTransaction/stash-dir/UserRequest.class.uniqueId8
  build/tmp/compileJava/compileTransaction/stash-dir/UserResponse$FindById.class.uniqueId5
  build/tmp/compileJava/compileTransaction/stash-dir/UserResponse.class.uniqueId0
  build/tmp/compileJava/compileTransaction/stash-dir/UserRestController.class.uniqueId3
  build/tmp/compileJava/compileTransaction/stash-dir/UserService.class.uniqueId11
  build/tmp/compileJava/previous-compilation-data.bin
  build/tmp/compileTestJava/compileTransaction/stash-dir/ReservationRestControllerTest.class.uniqueId0
  build/tmp/compileTestJava/previous-compilation-data.bin
  src/main/java/bdbe/bdbd/bay/Bay.java
  src/main/java/bdbe/bdbd/bay/BayJPARepository.java
  src/main/java/bdbe/bdbd/bay/BayRequest.java
  src/main/java/bdbe/bdbd/bay/BayResponse.java
  src/main/java/bdbe/bdbd/bay/BayRestController.java
  src/main/java/bdbe/bdbd/bay/BayService.java
  src/main/java/bdbe/bdbd/carwash/Carwash.java
  src/main/java/bdbe/bdbd/carwash/CarwashJPARepository.java
  src/main/java/bdbe/bdbd/reservation/Reservation.java
  src/main/java/bdbe/bdbd/reservation/ReservationJPARepository.java
  src/main/java/bdbe/bdbd/reservation/ReservationRequest.java
  src/main/java/bdbe/bdbd/reservation/ReservationResponse.java
  src/main/java/bdbe/bdbd/reservation/ReservationRestController.java
  src/main/java/bdbe/bdbd/reservation/ReservationService.java
  src/main/java/bdbe/bdbd/review/Review.java
  src/test/java/bdbe/bdbd/reservation/ReservationRestControllerTest.java
Labels: Type: Enhancement, Priority: High, Status: Done

#31 feat: 예약 기능 구현
  build/reports/tests/test/classes/bdbe.bdbd.reservation.ReservationRestControllerTest.html
  build/reports/tests/test/classes/bdbe.bdbd.review.ReviewRestControllerTest.html
  build/reports/tests/test/index.html
  build/reports/tests/test/packages/bdbe.bdbd.review.html
  build/test-results/test/TEST-bdbe.bdbd.reservation.ReservationRestControllerTest.xml
  build/test-results/test/TEST-bdbe.bdbd.review.ReviewRestControllerTest.xml
  build/test-results/test/binary/output.bin
  build/test-results/test/binary/output.bin.idx
  build/test-results/test/binary/results.bin
  build/tmp/compileJava/compileTransaction/stash-dir/BayJPARepository.class.uniqueId1
  build/tmp/compileJava/compileTransaction/stash-dir/ReservationJPARepository.class.uniqueId11
  build/tmp/compileJava/compileTransaction/stash-dir/ReservationRequest$SaveDTO$TimeDTO.class.uniqueId0
  build/tmp/compileJava/compileTransaction/stash-dir/ReservationRequest$SaveDTO.class.uniqueId8
  build/tmp/compileJava/compileTransaction/stash-dir/ReservationRequest$findAllRequestDTO.class.uniqueId7
  build/tmp/compileJava/compileTransaction/stash-dir/ReservationRequest.class.uniqueId4
  build/tmp/compileJava/compileTransaction/stash-dir/ReservationResponse$findAllResponseDTO$BayResponseDTO.class.uniqueId9
  build/tmp/compileJava/compileTransaction/stash-dir/ReservationResponse$findAllResponseDTO$BookedTimeDTO.class.uniqueId3
  build/tmp/compileJava/compileTransaction/stash-dir/ReservationResponse$findAllResponseDTO.class.uniqueId6
  build/tmp/compileJava/compileTransaction/stash-dir/ReservationResponse.class.uniqueId10
  build/tmp/compileJava/compileTransaction/stash-dir/ReservationRestController.class.uniqueId2
  build/tmp/compileJava/compileTransaction/stash-dir/ReservationService.class.uniqueId5
  build/tmp/compileJava/compileTransaction/stash-dir/ReviewRequest$SaveDTO.class.uniqueId2
  build/tmp/compileJava/compileTransaction/stash-dir/ReviewRequest.class.uniqueId3
  build/tmp/compileJava/compileTransaction/stash-dir/ReviewRestController.class.uniqueId1
  build/tmp/compileJava/compileTransaction/stash-dir/ReviewService.class.uniqueId0
  build/tmp/compileJava/previous-compilation-data.bin
  build/tmp/compileTestJava/compileTransaction/stash-dir/ReservationRestControllerTest.class.uniqueId0
  build/tmp/compileTestJava/compileTransaction/stash-dir/ReviewRestControllerTest.class.uniqueId0
  build/tmp/compileTestJava/previous-compilation-data.bin
  src/main/java/bdbe/bdbd/region/Region.java
  src/main/java/bdbe/bdbd/reservation/Reservation.java
  src/main/java/bdbe/bdbd/reservation/ReservationJPARepository.java
  src/main/java/bdbe/bdbd/reservation/ReservationResponse.java
  src/main/java/bdbe/bdbd/reservation/ReservationRestController.java
  src/main/java/bdbe/bdbd/reservation/ReservationService.java
  src/main/java/bdbe/bdbd/review/ReviewRequest.java
  src/main/java/bdbe/bdbd/review/ReviewService.java
  src/main/java/bdbe/bdbd/user/User.java
  src/test/java/bdbe/bdbd/reservation/ReservationRestControllerTest.java
  src/test/java/bdbe/bdbd/review/ReviewRestControllerTest.java
Labels: Type: Bug, Type: Enhancement, Priority: High, Status: In Progress

#33 feat: 베이 기능 구현
  src/main/java/bdbe/bdbd/bay/Bay.java
  src/main/java/bdbe/bdbd/bay/BayJPARepository.java
  src/main/java/bdbe/bdbd/bay/BayRequest.java
  src/main/java/bdbe/bdbd/bay/BayResponse.java
  src/main/java/bdbe/bdbd/bay/BayRestController.java
  src/main/java/bdbe/bdbd/bay/BayService.java
Labels: Type: Enhancement, Priority: Medium, Status: Done

#38 feat: 회원 권한 관리 및 로그인 회원가입 기능 구현 완료
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/spring-backlog.md
  src/main/java/bdbe/bdbd/_core/errors/security/CustomUserDetails.java
  src/main/java/bdbe/bdbd/_core/errors/security/JWTProvider.java
  src/main/java/bdbe/bdbd/_core/errors/security/SecurityConfig.java
  src/main/java/bdbe/bdbd/user/OwnerRestController.java
  src/main/java/bdbe/bdbd/user/OwnerService.java
  src/main/java/bdbe/bdbd/user/User.java
  src/main/java/bdbe/bdbd/user/UserRequest.java
  src/main/java/bdbe/bdbd/user/UserResponse.java
  src/main/java/bdbe/bdbd/user/UserRestController.java
  src/main/java/bdbe/bdbd/user/UserRole.java
  src/main/java/bdbe/bdbd/user/UserService.java
  src/test/java/bdbe/bdbd/review/ReviewRestControllerTest.java
  src/test/java/bdbe/bdbd/user/OwnerRestControllerTest.java
  src/test/java/bdbe/bdbd/user/UserRestControllerTest.java
Labels: Type: Enhancement, Priority: Medium, Status: Done

#43 delete: build directory 삭제
  build/reports/tests/test/css/base-style.css
  build/reports/tests/test/css/style.css
  build/reports/tests/test/index.html
  build/reports/tests/test/js/report.js
  build/test-results/test/binary/output.bin
  build/test-results/test/binary/output.bin.idx
  build/test-results/test/binary/results.bin
  build/tmp/compileJava/previous-compilation-data.bin
  build/tmp/compileTestJava/previous-compilation-data.bin
Labels: Priority: Urgent

#44 delete: build directory 삭제
  build/reports/tests/test/css/base-style.css
  build/reports/tests/test/css/style.css
  build/reports/tests/test/index.html
  build/reports/tests/test/js/report.js
  build/test-results/test/binary/output.bin
  build/test-results/test/binary/output.bin.idx
  build/test-results/test/binary/results.bin
  build/tmp/compileJava/previous-compilation-data.bin
  build/tmp/compileTestJava/previous-compilation-data.bin
Labels: Priority: Urgent

#45 delete: build directory 삭제
  build/reports/tests/test/index.html
  build/test-results/test/binary/output.bin
  build/test-results/test/binary/output.bin.idx
  build/test-results/test/binary/results.bin
  build/tmp/compileJava/compileTransaction/stash-dir/CustomUserDetails.class.uniqueId10
  build/tmp/compileJava/compileTransaction/stash-dir/CustomUserDetailsService.class.uniqueId7
  build/tmp/compileJava/compileTransaction/stash-dir/JWTProvider.class.uniqueId15
  build/tmp/compileJava/compileTransaction/stash-dir/JwtAuthenticationFilter.class.uniqueId6
  build/tmp/compileJava/compileTransaction/stash-dir/User$UserBuilder.class.uniqueId12
  build/tmp/compileJava/compileTransaction/stash-dir/User.class.uniqueId14
  build/tmp/compileJava/compileTransaction/stash-dir/UserJPARepository.class.uniqueId1
  build/tmp/compileJava/compileTransaction/stash-dir/UserRequest$EmailCheckDTO.class.uniqueId2
  build/tmp/compileJava/compileTransaction/stash-dir/UserRequest$JoinDTO.class.uniqueId9
  build/tmp/compileJava/compileTransaction/stash-dir/UserRequest$LoginDTO.class.uniqueId4
  build/tmp/compileJava/compileTransaction/stash-dir/UserRequest$UpdatePasswordDTO.class.uniqueId13
  build/tmp/compileJava/compileTransaction/stash-dir/UserRequest.class.uniqueId8
  build/tmp/compileJava/compileTransaction/stash-dir/UserResponse$FindById.class.uniqueId5
  build/tmp/compileJava/compileTransaction/stash-dir/UserResponse.class.uniqueId0
  build/tmp/compileJava/compileTransaction/stash-dir/UserRestController.class.uniqueId3
  build/tmp/compileJava/compileTransaction/stash-dir/UserService.class.uniqueId11
  build/tmp/compileJava/previous-compilation-data.bin
  build/tmp/compileTestJava/previous-compilation-data.bin
Labels: Priority: Urgent

#46 docs: README.md 업데이트
  README.md
Labels: Priority: Urgent, Status: Done

#47 docs: README.md 업데이트
  README.md
Labels: Priority: High, Status: Done

#53 refactor: 변경된 erd에 맞게 entity 수정
  src/main/java/bdbe/bdbd/_core/errors/security/JwtAuthenticationFilter.java
  src/main/java/bdbe/bdbd/bay/Bay.java
  src/main/java/bdbe/bdbd/bay/BayRequest.java
  src/main/java/bdbe/bdbd/bay/BayResponse.java
  src/main/java/bdbe/bdbd/carwash/Carwash.java
  src/main/java/bdbe/bdbd/carwash/CarwashRequest.java
  src/main/java/bdbe/bdbd/carwash/CarwashResponse.java
  src/main/java/bdbe/bdbd/carwash/CarwashService.java
  src/main/java/bdbe/bdbd/file/File.java
  src/main/java/bdbe/bdbd/keyword/Keyword.java
  src/main/java/bdbe/bdbd/location/Location.java
  src/main/java/bdbe/bdbd/location/RegionJPARepository.java
  src/main/java/bdbe/bdbd/optime/Optime.java
  src/main/java/bdbe/bdbd/region/RegionJPARepository.java
  src/main/java/bdbe/bdbd/reservation/Reservation.java
  src/main/java/bdbe/bdbd/reservation/ReservationResponse.java
  src/main/java/bdbe/bdbd/reservation/ReservationService.java
  src/main/java/bdbe/bdbd/review/Review.java
  src/main/java/bdbe/bdbd/review/ReviewJPARepository.java
  src/main/java/bdbe/bdbd/review/ReviewRequest.java
  src/main/java/bdbe/bdbd/review/ReviewResponse.java
  src/main/java/bdbe/bdbd/review/ReviewRestController.java
  src/main/java/bdbe/bdbd/review/ReviewService.java
  src/main/java/bdbe/bdbd/rkeyword/Rkeyword.java
  src/main/java/bdbe/bdbd/rkeyword/RkeywordJPARepository.java
  src/main/java/bdbe/bdbd/rkeyword/reviewKeyword/ReviewKeyword.java
  src/main/java/bdbe/bdbd/rkeyword/reviewKeyword/ReviewKeywordJPARepository.java
  src/main/java/bdbe/bdbd/user/User.java
  src/main/java/bdbe/bdbd/user/UserRequest.java
  src/main/java/bdbe/bdbd/user/UserService.java
  src/test/java/bdbe/bdbd/carwash/CarwashRestControllerTest.java
  src/test/java/bdbe/bdbd/reservation/ReservationRestControllerTest.java
  src/test/java/bdbe/bdbd/review/ReviewRestControllerTest.java
Labels: Type: Bug, Type: Enhancement, Priority: High, Status: Done

#54 merge: from weekly to develop
  src/main/java/bdbe/bdbd/_core/errors/security/JwtAuthenticationFilter.java
  src/main/java/bdbe/bdbd/bay/Bay.java
  src/main/java/bdbe/bdbd/bay/BayRequest.java
  src/main/java/bdbe/bdbd/bay/BayResponse.java
  src/main/java/bdbe/bdbd/carwash/Carwash.java
  src/main/java/bdbe/bdbd/carwash/CarwashRequest.java
  src/main/java/bdbe/bdbd/carwash/CarwashResponse.java
  src/main/java/bdbe/bdbd/carwash/CarwashService.java
  src/main/java/bdbe/bdbd/file/File.java
  src/main/java/bdbe/bdbd/keyword/Keyword.java
  src/main/java/bdbe/bdbd/location/Location.java
  src/main/java/bdbe/bdbd/location/RegionJPARepository.java
  src/main/java/bdbe/bdbd/optime/Optime.java
  src/main/java/bdbe/bdbd/region/RegionJPARepository.java
  src/main/java/bdbe/bdbd/reservation/Reservation.java
  src/main/java/bdbe/bdbd/reservation/ReservationResponse.java
  src/main/java/bdbe/bdbd/reservation/ReservationService.java
  src/main/java/bdbe/bdbd/review/Review.java
  src/main/java/bdbe/bdbd/review/ReviewJPARepository.java
  src/main/java/bdbe/bdbd/review/ReviewRequest.java
  src/main/java/bdbe/bdbd/review/ReviewResponse.java
  src/main/java/bdbe/bdbd/review/ReviewRestController.java
  src/main/java/bdbe/bdbd/review/ReviewService.java
  src/main/java/bdbe/bdbd/rkeyword/Rkeyword.java
  src/main/java/bdbe/bdbd/rkeyword/RkeywordJPARepository.java
  src/main/java/bdbe/bdbd/rkeyword/reviewKeyword/ReviewKeyword.java
  src/main/java/bdbe/bdbd/rkeyword/reviewKeyword/ReviewKeywordJPARepository.java
  src/main/java/bdbe/bdbd/user/User.java
  src/main/java/bdbe/bdbd/user/UserRequest.java
  src/main/java/bdbe/bdbd/user/UserService.java
  src/test/java/bdbe/bdbd/carwash/CarwashRestControllerTest.java
  src/test/java/bdbe/bdbd/reservation/ReservationRestControllerTest.java
  src/test/java/bdbe/bdbd/review/ReviewRestControllerTest.java
Labels: Type: Bug, Type: Enhancement, Priority: Medium, Status: Done

#55 merge: develop to master
  src/main/java/bdbe/bdbd/_core/errors/security/JwtAuthenticationFilter.java
  src/main/java/bdbe/bdbd/bay/Bay.java
  src/main/java/bdbe/bdbd/bay/BayRequest.java
  src/main/java/bdbe/bdbd/bay/BayResponse.java
  src/main/java/bdbe/bdbd/carwash/Carwash.java
  src/main/java/bdbe/bdbd/carwash/CarwashRequest.java
  src/main/java/bdbe/bdbd/carwash/CarwashResponse.java
  src/main/java/bdbe/bdbd/carwash/CarwashService.java
  src/main/java/bdbe/bdbd/file/File.java
  src/main/java/bdbe/bdbd/keyword/Keyword.java
  src/main/java/bdbe/bdbd/location/Location.java
  src/main/java/bdbe/bdbd/location/RegionJPARepository.java
  src/main/java/bdbe/bdbd/optime/Optime.java
  src/main/java/bdbe/bdbd/region/RegionJPARepository.java
  src/main/java/bdbe/bdbd/reservation/Reservation.java
  src/main/java/bdbe/bdbd/reservation/ReservationResponse.java
  src/main/java/bdbe/bdbd/reservation/ReservationService.java
  src/main/java/bdbe/bdbd/review/Review.java
  src/main/java/bdbe/bdbd/review/ReviewJPARepository.java
  src/main/java/bdbe/bdbd/review/ReviewRequest.java
  src/main/java/bdbe/bdbd/review/ReviewResponse.java
  src/main/java/bdbe/bdbd/review/ReviewRestController.java
  src/main/java/bdbe/bdbd/review/ReviewService.java
  src/main/java/bdbe/bdbd/rkeyword/Rkeyword.java
  src/main/java/bdbe/bdbd/rkeyword/RkeywordJPARepository.java
  src/main/java/bdbe/bdbd/rkeyword/reviewKeyword/ReviewKeyword.java
  src/main/java/bdbe/bdbd/rkeyword/reviewKeyword/ReviewKeywordJPARepository.java
  src/main/java/bdbe/bdbd/user/User.java
  src/main/java/bdbe/bdbd/user/UserRequest.java
  src/main/java/bdbe/bdbd/user/UserService.java
  src/test/java/bdbe/bdbd/carwash/CarwashRestControllerTest.java
  src/test/java/bdbe/bdbd/reservation/ReservationRestControllerTest.java
  src/test/java/bdbe/bdbd/review/ReviewRestControllerTest.java
Labels: Priority: Medium

#58 refactor: 변경된 erd를 반영한 entity 수정
  src/main/java/bdbe/bdbd/BdbdApplication.java
  src/main/java/bdbe/bdbd/carwash/CarwashRequest.java
  src/main/java/bdbe/bdbd/carwash/CarwashService.java
  src/main/java/bdbe/bdbd/file/File.java
  src/main/java/bdbe/bdbd/keyword/Keyword.java
  src/main/java/bdbe/bdbd/keyword/reviewKeyword/ReviewKeyword.java
  src/main/java/bdbe/bdbd/keyword/reviewKeyword/ReviewKeywordJPARepository.java
  src/main/java/bdbe/bdbd/location/Location.java
  src/main/java/bdbe/bdbd/location/LocationJPARepository.java
  src/main/java/bdbe/bdbd/optime/Optime.java
  src/main/java/bdbe/bdbd/reservation/Reservation.java
  src/main/java/bdbe/bdbd/reservation/ReservationRequest.java
  src/main/java/bdbe/bdbd/reservation/ReservationResponse.java
  src/main/java/bdbe/bdbd/reservation/ReservationService.java
  src/main/java/bdbe/bdbd/review/Review.java
  src/main/java/bdbe/bdbd/review/ReviewResponse.java
  src/main/java/bdbe/bdbd/review/ReviewService.java
  src/main/java/bdbe/bdbd/user/User.java
  src/test/java/bdbe/bdbd/carwash/CarwashRestControllerTest.java
  src/test/java/bdbe/bdbd/reservation/ReservationRestControllerTest.java
  src/test/java/bdbe/bdbd/review/ReviewRestControllerTest.java
Labels: Type: Bug, Type: Enhancement, Priority: High, Status: Done

#60 refactor: User와 Owenr 엔티티 및 테스트 ERD변경에 맞추어 수정
  src/main/java/bdbe/bdbd/user/OwnerService.java
  src/main/java/bdbe/bdbd/user/User.java
  src/main/java/bdbe/bdbd/user/UserRequest.java
  src/test/java/bdbe/bdbd/user/OwnerRestControllerTest.java
  src/test/java/bdbe/bdbd/user/UserRestControllerTest.java
Labels: Type: Enhancement, Priority: Medium, Status: Done

#63 merge: from weekly to develop
  src/main/java/bdbe/bdbd/BdbdApplication.java
  src/main/java/bdbe/bdbd/bay/BayRequest.java
  src/main/java/bdbe/bdbd/bay/BayRestController.java
  src/main/java/bdbe/bdbd/carwash/CarwashRequest.java
  src/main/java/bdbe/bdbd/carwash/CarwashService.java
  src/main/java/bdbe/bdbd/file/File.java
  src/main/java/bdbe/bdbd/keyword/Keyword.java
  src/main/java/bdbe/bdbd/keyword/reviewKeyword/ReviewKeyword.java
  src/main/java/bdbe/bdbd/keyword/reviewKeyword/ReviewKeywordJPARepository.java
  src/main/java/bdbe/bdbd/location/Location.java
  src/main/java/bdbe/bdbd/location/LocationJPARepository.java
  src/main/java/bdbe/bdbd/optime/Optime.java
  src/main/java/bdbe/bdbd/reservation/Reservation.java
  src/main/java/bdbe/bdbd/reservation/ReservationRequest.java
  src/main/java/bdbe/bdbd/reservation/ReservationResponse.java
  src/main/java/bdbe/bdbd/reservation/ReservationService.java
  src/main/java/bdbe/bdbd/review/Review.java
  src/main/java/bdbe/bdbd/review/ReviewResponse.java
  src/main/java/bdbe/bdbd/review/ReviewService.java
  src/main/java/bdbe/bdbd/user/OwnerService.java
  src/main/java/bdbe/bdbd/user/User.java
  src/main/java/bdbe/bdbd/user/UserRequest.java
  src/test/java/bdbe/bdbd/bay/BayRestControllerTest.java
  src/test/java/bdbe/bdbd/carwash/CarwashRestControllerTest.java
  src/test/java/bdbe/bdbd/reservation/ReservationRestControllerTest.java
  src/test/java/bdbe/bdbd/review/ReviewRestControllerTest.java
  src/test/java/bdbe/bdbd/user/OwnerRestControllerTest.java
  src/test/java/bdbe/bdbd/user/UserRestControllerTest.java
Labels: Type: Enhancement, Priority: Medium, Status: Done

#64 merge: from develop to master
  src/main/java/bdbe/bdbd/BdbdApplication.java
  src/main/java/bdbe/bdbd/bay/BayRequest.java
  src/main/java/bdbe/bdbd/bay/BayRestController.java
  src/main/java/bdbe/bdbd/carwash/CarwashRequest.java
  src/main/java/bdbe/bdbd/carwash/CarwashService.java
  src/main/java/bdbe/bdbd/file/File.java
  src/main/java/bdbe/bdbd/keyword/Keyword.java
  src/main/java/bdbe/bdbd/keyword/reviewKeyword/ReviewKeyword.java
  src/main/java/bdbe/bdbd/keyword/reviewKeyword/ReviewKeywordJPARepository.java
  src/main/java/bdbe/bdbd/location/Location.java
  src/main/java/bdbe/bdbd/location/LocationJPARepository.java
  src/main/java/bdbe/bdbd/optime/Optime.java
  src/main/java/bdbe/bdbd/reservation/Reservation.java
  src/main/java/bdbe/bdbd/reservation/ReservationRequest.java
  src/main/java/bdbe/bdbd/reservation/ReservationResponse.java
  src/main/java/bdbe/bdbd/reservation/ReservationService.java
  src/main/java/bdbe/bdbd/review/Review.java
  src/main/java/bdbe/bdbd/review/ReviewResponse.java
  src/main/java/bdbe/bdbd/review/ReviewService.java
  src/main/java/bdbe/bdbd/user/OwnerService.java
  src/main/java/bdbe/bdbd/user/User.java
  src/main/java/bdbe/bdbd/user/UserRequest.java
  src/test/java/bdbe/bdbd/bay/BayRestControllerTest.java
  src/test/java/bdbe/bdbd/carwash/CarwashRestControllerTest.java
  src/test/java/bdbe/bdbd/reservation/ReservationRestControllerTest.java
  src/test/java/bdbe/bdbd/review/ReviewRestControllerTest.java
  src/test/java/bdbe/bdbd/user/OwnerRestControllerTest.java
  src/test/java/bdbe/bdbd/user/UserRestControllerTest.java
Labels: Priority: High

#66 refactor: 코드 작동되도록 리팩토링 및 버그 수정
  src/main/java/bdbe/bdbd/bay/BayRestController.java
  src/main/java/bdbe/bdbd/bay/BayService.java
  src/main/java/bdbe/bdbd/carwash/Carwash.java
  src/main/java/bdbe/bdbd/keyword/KeywordJPARepository.java
  src/main/java/bdbe/bdbd/location/LocationJPARepository.java
  src/main/java/bdbe/bdbd/optime/Optime.java
  src/main/java/bdbe/bdbd/optime/OptimeJPARepository.java
  src/main/java/bdbe/bdbd/reservation/Reservation.java
  src/main/java/bdbe/bdbd/reservation/ReservationJPARepository.java
  src/main/java/bdbe/bdbd/reservation/ReservationResponse.java
  src/main/java/bdbe/bdbd/reservation/ReservationRestController.java
  src/main/java/bdbe/bdbd/reservation/ReservationService.java
  src/main/java/bdbe/bdbd/review/ReviewRequest.java
  src/main/java/bdbe/bdbd/review/ReviewResponse.java
  src/main/java/bdbe/bdbd/review/ReviewRestController.java
  src/main/java/bdbe/bdbd/review/ReviewService.java
  src/main/java/bdbe/bdbd/user/UserJPARepository.java
  src/test/java/bdbe/bdbd/bay/BayRestControllerTest.java
  src/test/java/bdbe/bdbd/carwash/CarwashRestControllerTest.java
  src/test/java/bdbe/bdbd/reservation/ReservationRestControllerTest.java
  src/test/java/bdbe/bdbd/review/ReviewRestControllerTest.java
  src/test/java/bdbe/bdbd/user/OwnerRestControllerTest.java
Labels: Type: Bug, Type: Enhancement, Priority: High, Status: Done

#68 feat: 세차장 위치 및 키워드 검색 기능 구현 및 유저 리팩토링
  src/main/java/bdbe/bdbd/_core/errors/security/CustomUserDetails.java
  src/main/java/bdbe/bdbd/_core/errors/security/JWTProvider.java
  src/main/java/bdbe/bdbd/_core/errors/security/JwtAuthenticationFilter.java
  src/main/java/bdbe/bdbd/_core/errors/security/SecurityConfig.java
  src/main/java/bdbe/bdbd/_core/errors/utils/Haversine.java
  src/main/java/bdbe/bdbd/carwash/CarwashJPARepository.java
  src/main/java/bdbe/bdbd/carwash/CarwashRequest.java
  src/main/java/bdbe/bdbd/carwash/CarwashRestController.java
  src/main/java/bdbe/bdbd/carwash/CarwashService.java
  src/main/java/bdbe/bdbd/keyword/carwashKeyword/CarwashKeywordJPARepository.java
  src/main/java/bdbe/bdbd/user/User.java
  src/test/java/bdbe/bdbd/carwash/CarwashRestControllerTest.java
  src/test/java/bdbe/bdbd/user/OwnerRestControllerTest.java
  src/test/java/bdbe/bdbd/user/UserRestControllerTest.java
Labels: Priority: High, Status: Done

#56 전남대_10조_뽀득뽀득_5주차
  src/main/java/bdbe/bdbd/BdbdApplication.java
  src/main/java/bdbe/bdbd/_core/errors/security/JwtAuthenticationFilter.java
  src/main/java/bdbe/bdbd/bay/Bay.java
  src/main/java/bdbe/bdbd/bay/BayRequest.java
  src/main/java/bdbe/bdbd/bay/BayResponse.java
  src/main/java/bdbe/bdbd/bay/BayRestController.java
  src/main/java/bdbe/bdbd/carwash/Carwash.java
  src/main/java/bdbe/bdbd/carwash/CarwashRequest.java
  src/main/java/bdbe/bdbd/carwash/CarwashResponse.java
  src/main/java/bdbe/bdbd/carwash/CarwashService.java
  src/main/java/bdbe/bdbd/file/File.java
  src/main/java/bdbe/bdbd/keyword/Keyword.java
  src/main/java/bdbe/bdbd/keyword/reviewKeyword/ReviewKeyword.java
  src/main/java/bdbe/bdbd/keyword/reviewKeyword/ReviewKeywordJPARepository.java
  src/main/java/bdbe/bdbd/location/Location.java
  src/main/java/bdbe/bdbd/location/LocationJPARepository.java
  src/main/java/bdbe/bdbd/optime/Optime.java
  src/main/java/bdbe/bdbd/region/RegionJPARepository.java
  src/main/java/bdbe/bdbd/reservation/Reservation.java
  src/main/java/bdbe/bdbd/reservation/ReservationRequest.java
  src/main/java/bdbe/bdbd/reservation/ReservationResponse.java
  src/main/java/bdbe/bdbd/reservation/ReservationService.java
  src/main/java/bdbe/bdbd/review/Review.java
  src/main/java/bdbe/bdbd/review/ReviewJPARepository.java
  src/main/java/bdbe/bdbd/review/ReviewRequest.java
  src/main/java/bdbe/bdbd/review/ReviewResponse.java
  src/main/java/bdbe/bdbd/review/ReviewRestController.java
  src/main/java/bdbe/bdbd/review/ReviewService.java
  src/main/java/bdbe/bdbd/rkeyword/Rkeyword.java
  src/main/java/bdbe/bdbd/rkeyword/RkeywordJPARepository.java
  src/main/java/bdbe/bdbd/user/OwnerService.java
  src/main/java/bdbe/bdbd/user/User.java
  src/main/java/bdbe/bdbd/user/UserRequest.java
  src/main/java/bdbe/bdbd/user/UserService.java
  src/test/java/bdbe/bdbd/bay/BayRestControllerTest.java
  src/test/java/bdbe/bdbd/carwash/CarwashRestControllerTest.java
  src/test/java/bdbe/bdbd/reservation/ReservationRestControllerTest.java
  src/test/java/bdbe/bdbd/review/ReviewRestControllerTest.java
  src/test/java/bdbe/bdbd/user/OwnerRestControllerTest.java
  src/test/java/bdbe/bdbd/user/UserRestControllerTest.java
Labels: Type: Enhancement, Priority: High, Status: In Progress, Request Review

#69 feat: 세차장 상세 정보 기능 구현
  src/main/java/bdbe/bdbd/carwash/CarwashJPARepository.java
  src/main/java/bdbe/bdbd/carwash/CarwashResponse.java
  src/main/java/bdbe/bdbd/carwash/CarwashRestController.java
  src/main/java/bdbe/bdbd/carwash/CarwashService.java
  src/main/java/bdbe/bdbd/keyword/carwashKeyword/CarwashKeywordJPARepository.java
  src/test/java/bdbe/bdbd/carwash/CarwashRestControllerTest.java
Labels: Priority: High

#73 fix: 시큐리티 권한 "ROLE_" 하드코딩 수정
  src/main/java/bdbe/bdbd/_core/errors/security/CustomUserDetails.java
  src/main/java/bdbe/bdbd/_core/errors/security/JwtAuthenticationFilter.java
  src/main/java/bdbe/bdbd/_core/errors/security/SecurityConfig.java
  src/main/java/bdbe/bdbd/carwash/CarwashRequest.java
  src/main/java/bdbe/bdbd/carwash/CarwashService.java
  src/main/java/bdbe/bdbd/file/File.java
Labels: Type: Enhancement, Priority: High, Status: Done

#74 feat: 예약 수정 및 취소 기능 구현
  src/main/java/bdbe/bdbd/bay/Bay.java
  src/main/java/bdbe/bdbd/bay/BayResponse.java
  src/main/java/bdbe/bdbd/bay/BayRestController.java
  src/main/java/bdbe/bdbd/file/File.java
  src/main/java/bdbe/bdbd/keyword/reviewKeyword/ReviewKeywordJPARepository.java
  src/main/java/bdbe/bdbd/reservation/Reservation.java
  src/main/java/bdbe/bdbd/reservation/ReservationRequest.java
  src/main/java/bdbe/bdbd/reservation/ReservationRestController.java
  src/main/java/bdbe/bdbd/reservation/ReservationService.java
  src/main/java/bdbe/bdbd/review/ReviewJPARepository.java
  src/test/java/bdbe/bdbd/carwash/CarwashRestControllerTest.java
  src/test/java/bdbe/bdbd/reservation/ReservationRestControllerTest.java
  src/test/java/bdbe/bdbd/review/ReviewRestControllerTest.java
Labels: Type: Enhancement, Priority: Medium, Status: Done

#72 feat: 6주차 기능 구현 및 리팩토링
  src/main/java/bdbe/bdbd/_core/errors/security/CustomUserDetails.java
  src/main/java/bdbe/bdbd/_core/errors/security/JWTProvider.java
  src/main/java/bdbe/bdbd/_core/errors/security/JwtAuthenticationFilter.java
  src/main/java/bdbe/bdbd/_core/errors/security/SecurityConfig.java
  src/main/java/bdbe/bdbd/_core/errors/utils/Haversine.java
  src/main/java/bdbe/bdbd/bay/BayRestController.java
  src/main/java/bdbe/bdbd/bay/BayService.java
  src/main/java/bdbe/bdbd/carwash/Carwash.java
  src/main/java/bdbe/bdbd/carwash/CarwashJPARepository.java
  src/main/java/bdbe/bdbd/carwash/CarwashRequest.java
  src/main/java/bdbe/bdbd/carwash/CarwashResponse.java
  src/main/java/bdbe/bdbd/carwash/CarwashRestController.java
  src/main/java/bdbe/bdbd/carwash/CarwashService.java
  src/main/java/bdbe/bdbd/keyword/KeywordJPARepository.java
  src/main/java/bdbe/bdbd/keyword/carwashKeyword/CarwashKeywordJPARepository.java
  src/main/java/bdbe/bdbd/location/LocationJPARepository.java
  src/main/java/bdbe/bdbd/optime/Optime.java
  src/main/java/bdbe/bdbd/optime/OptimeJPARepository.java
  src/main/java/bdbe/bdbd/reservation/Reservation.java
  src/main/java/bdbe/bdbd/reservation/ReservationJPARepository.java
  src/main/java/bdbe/bdbd/reservation/ReservationRequest.java
  src/main/java/bdbe/bdbd/reservation/ReservationResponse.java
  src/main/java/bdbe/bdbd/reservation/ReservationRestController.java
  src/main/java/bdbe/bdbd/reservation/ReservationService.java
  src/main/java/bdbe/bdbd/review/Review.java
  src/main/java/bdbe/bdbd/review/ReviewRequest.java
  src/main/java/bdbe/bdbd/review/ReviewResponse.java
  src/main/java/bdbe/bdbd/review/ReviewRestController.java
  src/main/java/bdbe/bdbd/review/ReviewService.java
  src/main/java/bdbe/bdbd/user/User.java
  src/main/java/bdbe/bdbd/user/UserJPARepository.java
  src/test/java/bdbe/bdbd/bay/BayRestControllerTest.java
  src/test/java/bdbe/bdbd/carwash/CarwashRestControllerTest.java
  src/test/java/bdbe/bdbd/reservation/ReservationRestControllerTest.java
  src/test/java/bdbe/bdbd/review/ReviewRestControllerTest.java
  src/test/java/bdbe/bdbd/user/OwnerRestControllerTest.java
  src/test/java/bdbe/bdbd/user/UserRestControllerTest.java
Labels: Type: Bug, Type: Enhancement, Priority: High, Status: Done

#77 refactor: 예약 취소 리팩토링
  src/main/java/bdbe/bdbd/carwash/Carwash.java
  src/main/java/bdbe/bdbd/reservation/Reservation.java
  src/main/java/bdbe/bdbd/reservation/ReservationService.java
  src/test/java/bdbe/bdbd/reservation/ReservationRestControllerTest.java
Labels: Type: Bug, Type: Enhancement, Priority: High, Status: Done

#79 feat: 세차장 정보 수정 기능
  src/main/java/bdbe/bdbd/carwash/Carwash.java
  src/main/java/bdbe/bdbd/carwash/CarwashRequest.java
  src/main/java/bdbe/bdbd/carwash/CarwashResponse.java
  src/main/java/bdbe/bdbd/carwash/CarwashRestController.java
  src/main/java/bdbe/bdbd/carwash/CarwashService.java
  src/main/java/bdbe/bdbd/location/Location.java
  src/main/java/bdbe/bdbd/optime/Optime.java
  src/main/java/bdbe/bdbd/optime/OptimeJPARepository.java
  src/test/java/bdbe/bdbd/carwash/CarwashRestControllerTest.java
Labels: Type: Bug, Type: Enhancement, Priority: High, Status: In Progress

#80 refactor: 코드 리뷰 피드백 반영 및 프론트 api 요구사항 반영
  src/main/java/bdbe/bdbd/_core/errors/utils/DateUtils.java
  src/main/java/bdbe/bdbd/_core/errors/utils/KeywordTypeConverter.java
  src/main/java/bdbe/bdbd/bay/BayJPARepository.java
  src/main/java/bdbe/bdbd/carwash/CarwashJPARepository.java
  src/main/java/bdbe/bdbd/carwash/CarwashResponse.java
  src/main/java/bdbe/bdbd/carwash/CarwashRestController.java
  src/main/java/bdbe/bdbd/keyword/Keyword.java
  src/main/java/bdbe/bdbd/keyword/KeywordJPARepository.java
  src/main/java/bdbe/bdbd/keyword/KeywordType.java
  src/main/java/bdbe/bdbd/reservation/ReservationJPARepository.java
  src/main/java/bdbe/bdbd/reservation/ReservationService.java
  src/main/java/bdbe/bdbd/review/ReviewJPARepository.java
  src/main/java/bdbe/bdbd/review/ReviewResponse.java
  src/main/java/bdbe/bdbd/review/ReviewService.java
  src/main/java/bdbe/bdbd/user/OwnerResponse.java
  src/main/java/bdbe/bdbd/user/OwnerService.java
  src/test/java/bdbe/bdbd/carwash/CarwashRestControllerTest.java
  src/test/java/bdbe/bdbd/reservation/ReservationRestControllerTest.java
  src/test/java/bdbe/bdbd/review/ReviewRestControllerTest.java
  src/test/java/bdbe/bdbd/user/OwnerRestControllerTest.java
Labels: Type: Bug, Type: Enhancement, Priority: High, Status: Available

#81 feat: 파일 업로드 기능
  build.gradle
  src/main/java/bdbe/bdbd/_core/errors/utils/AWSConfig.java
  src/main/java/bdbe/bdbd/carwash/CarwashRestController.java
  src/main/java/bdbe/bdbd/file/File.java
  src/main/java/bdbe/bdbd/file/FileJPARepository.java
  src/main/java/bdbe/bdbd/file/FileRequest.java
  src/main/java/bdbe/bdbd/file/FileResponse.java
  src/main/java/bdbe/bdbd/file/FileRestController.java
  src/main/java/bdbe/bdbd/file/FileService.java
  src/main/java/bdbe/bdbd/user/UserService.java
  src/test/java/bdbe/bdbd/carwash/CarwashRestControllerTest.java
  src/test/java/bdbe/bdbd/file/FileRestControllerTest.java
Labels: Type: Enhancement, Priority: High, Status: Done

#82 fix: 세차장 수정 버그 제거 및 리팩토링
  src/main/java/bdbe/bdbd/carwash/CarwashRequest.java
  src/main/java/bdbe/bdbd/carwash/CarwashResponse.java
  src/main/java/bdbe/bdbd/carwash/CarwashRestController.java
  src/main/java/bdbe/bdbd/carwash/CarwashService.java
  src/main/java/bdbe/bdbd/keyword/carwashKeyword/CarwashKeywordJPARepository.java
  src/main/java/bdbe/bdbd/location/Location.java
  src/test/java/bdbe/bdbd/carwash/CarwashRestControllerTest.java
Labels: Type: Bug, Type: Enhancement, Priority: High, Status: Done

#83 merge: from weekly to develop
  build.gradle
  src/main/java/bdbe/bdbd/_core/errors/security/CustomUserDetails.java
  src/main/java/bdbe/bdbd/_core/errors/security/JwtAuthenticationFilter.java
  src/main/java/bdbe/bdbd/_core/errors/security/SecurityConfig.java
  src/main/java/bdbe/bdbd/_core/errors/utils/AWSConfig.java
  src/main/java/bdbe/bdbd/_core/errors/utils/DateUtils.java
  src/main/java/bdbe/bdbd/_core/errors/utils/KeywordTypeConverter.java
  src/main/java/bdbe/bdbd/bay/Bay.java
  src/main/java/bdbe/bdbd/bay/BayJPARepository.java
  src/main/java/bdbe/bdbd/bay/BayResponse.java
  src/main/java/bdbe/bdbd/bay/BayRestController.java
  src/main/java/bdbe/bdbd/carwash/Carwash.java
  src/main/java/bdbe/bdbd/carwash/CarwashJPARepository.java
  src/main/java/bdbe/bdbd/carwash/CarwashRequest.java
  src/main/java/bdbe/bdbd/carwash/CarwashResponse.java
  src/main/java/bdbe/bdbd/carwash/CarwashRestController.java
  src/main/java/bdbe/bdbd/carwash/CarwashService.java
  src/main/java/bdbe/bdbd/file/File.java
  src/main/java/bdbe/bdbd/file/FileJPARepository.java
  src/main/java/bdbe/bdbd/file/FileRequest.java
  src/main/java/bdbe/bdbd/file/FileResponse.java
  src/main/java/bdbe/bdbd/file/FileRestController.java
  src/main/java/bdbe/bdbd/file/FileService.java
  src/main/java/bdbe/bdbd/keyword/Keyword.java
  src/main/java/bdbe/bdbd/keyword/KeywordJPARepository.java
  src/main/java/bdbe/bdbd/keyword/KeywordType.java
  src/main/java/bdbe/bdbd/keyword/carwashKeyword/CarwashKeywordJPARepository.java
  src/main/java/bdbe/bdbd/keyword/reviewKeyword/ReviewKeywordJPARepository.java
  src/main/java/bdbe/bdbd/location/Location.java
  src/main/java/bdbe/bdbd/optime/Optime.java
  src/main/java/bdbe/bdbd/optime/OptimeJPARepository.java
  src/main/java/bdbe/bdbd/reservation/Reservation.java
  src/main/java/bdbe/bdbd/reservation/ReservationJPARepository.java
  src/main/java/bdbe/bdbd/reservation/ReservationRequest.java
  src/main/java/bdbe/bdbd/reservation/ReservationRestController.java
  src/main/java/bdbe/bdbd/reservation/ReservationService.java
  src/main/java/bdbe/bdbd/review/ReviewJPARepository.java
  src/main/java/bdbe/bdbd/review/ReviewResponse.java
  src/main/java/bdbe/bdbd/review/ReviewService.java
  src/main/java/bdbe/bdbd/user/OwnerRequest.java
  src/main/java/bdbe/bdbd/user/OwnerResponse.java
  src/main/java/bdbe/bdbd/user/OwnerRestController.java
  src/main/java/bdbe/bdbd/user/OwnerService.java
  src/main/java/bdbe/bdbd/user/UserService.java
  src/test/java/bdbe/bdbd/bay/BayRestControllerTest.java
  src/test/java/bdbe/bdbd/carwash/CarwashRestControllerTest.java
  src/test/java/bdbe/bdbd/file/FileRestControllerTest.java
  src/test/java/bdbe/bdbd/reservation/ReservationRestControllerTest.java
  src/test/java/bdbe/bdbd/review/ReviewRestControllerTest.java
  src/test/java/bdbe/bdbd/user/OwnerRestControllerTest.java
Labels: Type: Enhancement, Priority: High, Status: Done

#84 merge: from develop to master
  build.gradle
  src/main/java/bdbe/bdbd/_core/errors/security/CustomUserDetails.java
  src/main/java/bdbe/bdbd/_core/errors/security/JwtAuthenticationFilter.java
  src/main/java/bdbe/bdbd/_core/errors/security/SecurityConfig.java
  src/main/java/bdbe/bdbd/_core/errors/utils/AWSConfig.java
  src/main/java/bdbe/bdbd/_core/errors/utils/DateUtils.java
  src/main/java/bdbe/bdbd/_core/errors/utils/KeywordTypeConverter.java
  src/main/java/bdbe/bdbd/bay/Bay.java
  src/main/java/bdbe/bdbd/bay/BayJPARepository.java
  src/main/java/bdbe/bdbd/bay/BayResponse.java
  src/main/java/bdbe/bdbd/bay/BayRestController.java
  src/main/java/bdbe/bdbd/carwash/Carwash.java
  src/main/java/bdbe/bdbd/carwash/CarwashJPARepository.java
  src/main/java/bdbe/bdbd/carwash/CarwashRequest.java
  src/main/java/bdbe/bdbd/carwash/CarwashResponse.java
  src/main/java/bdbe/bdbd/carwash/CarwashRestController.java
  src/main/java/bdbe/bdbd/carwash/CarwashService.java
  src/main/java/bdbe/bdbd/file/File.java
  src/main/java/bdbe/bdbd/file/FileJPARepository.java
  src/main/java/bdbe/bdbd/file/FileRequest.java
  src/main/java/bdbe/bdbd/file/FileResponse.java
  src/main/java/bdbe/bdbd/file/FileRestController.java
  src/main/java/bdbe/bdbd/file/FileService.java
  src/main/java/bdbe/bdbd/keyword/Keyword.java
  src/main/java/bdbe/bdbd/keyword/KeywordJPARepository.java
  src/main/java/bdbe/bdbd/keyword/KeywordType.java
  src/main/java/bdbe/bdbd/keyword/carwashKeyword/CarwashKeywordJPARepository.java
  src/main/java/bdbe/bdbd/keyword/reviewKeyword/ReviewKeywordJPARepository.java
  src/main/java/bdbe/bdbd/location/Location.java
  src/main/java/bdbe/bdbd/optime/Optime.java
  src/main/java/bdbe/bdbd/optime/OptimeJPARepository.java
  src/main/java/bdbe/bdbd/reservation/Reservation.java
  src/main/java/bdbe/bdbd/reservation/ReservationJPARepository.java
  src/main/java/bdbe/bdbd/reservation/ReservationRequest.java
  src/main/java/bdbe/bdbd/reservation/ReservationRestController.java
  src/main/java/bdbe/bdbd/reservation/ReservationService.java
  src/main/java/bdbe/bdbd/review/ReviewJPARepository.java
  src/main/java/bdbe/bdbd/review/ReviewResponse.java
  src/main/java/bdbe/bdbd/review/ReviewService.java
  src/main/java/bdbe/bdbd/user/OwnerRequest.java
  src/main/java/bdbe/bdbd/user/OwnerResponse.java
  src/main/java/bdbe/bdbd/user/OwnerRestController.java
  src/main/java/bdbe/bdbd/user/OwnerService.java
  src/main/java/bdbe/bdbd/user/UserService.java
  src/test/java/bdbe/bdbd/bay/BayRestControllerTest.java
  src/test/java/bdbe/bdbd/carwash/CarwashRestControllerTest.java
  src/test/java/bdbe/bdbd/file/FileRestControllerTest.java
  src/test/java/bdbe/bdbd/reservation/ReservationRestControllerTest.java
  src/test/java/bdbe/bdbd/review/ReviewRestControllerTest.java
  src/test/java/bdbe/bdbd/user/OwnerRestControllerTest.java
Labels: Type: Enhancement, Priority: High, Status: Done

#85 전남대_10조_뽀득뽀득_7주차
  build.gradle
  src/main/java/bdbe/bdbd/_core/errors/security/CustomUserDetails.java
  src/main/java/bdbe/bdbd/_core/errors/security/JwtAuthenticationFilter.java
  src/main/java/bdbe/bdbd/_core/errors/security/SecurityConfig.java
  src/main/java/bdbe/bdbd/_core/errors/utils/AWSConfig.java
  src/main/java/bdbe/bdbd/_core/errors/utils/DateUtils.java
  src/main/java/bdbe/bdbd/_core/errors/utils/KeywordTypeConverter.java
  src/main/java/bdbe/bdbd/bay/Bay.java
  src/main/java/bdbe/bdbd/bay/BayJPARepository.java
  src/main/java/bdbe/bdbd/bay/BayResponse.java
  src/main/java/bdbe/bdbd/bay/BayRestController.java
  src/main/java/bdbe/bdbd/carwash/Carwash.java
  src/main/java/bdbe/bdbd/carwash/CarwashJPARepository.java
  src/main/java/bdbe/bdbd/carwash/CarwashRequest.java
  src/main/java/bdbe/bdbd/carwash/CarwashResponse.java
  src/main/java/bdbe/bdbd/carwash/CarwashRestController.java
  src/main/java/bdbe/bdbd/carwash/CarwashService.java
  src/main/java/bdbe/bdbd/file/File.java
  src/main/java/bdbe/bdbd/file/FileJPARepository.java
  src/main/java/bdbe/bdbd/file/FileRequest.java
  src/main/java/bdbe/bdbd/file/FileResponse.java
  src/main/java/bdbe/bdbd/file/FileRestController.java
  src/main/java/bdbe/bdbd/file/FileService.java
  src/main/java/bdbe/bdbd/keyword/Keyword.java
  src/main/java/bdbe/bdbd/keyword/KeywordJPARepository.java
  src/main/java/bdbe/bdbd/keyword/KeywordType.java
  src/main/java/bdbe/bdbd/keyword/carwashKeyword/CarwashKeywordJPARepository.java
  src/main/java/bdbe/bdbd/keyword/reviewKeyword/ReviewKeywordJPARepository.java
  src/main/java/bdbe/bdbd/location/Location.java
  src/main/java/bdbe/bdbd/optime/Optime.java
  src/main/java/bdbe/bdbd/optime/OptimeJPARepository.java
  src/main/java/bdbe/bdbd/reservation/Reservation.java
  src/main/java/bdbe/bdbd/reservation/ReservationJPARepository.java
  src/main/java/bdbe/bdbd/reservation/ReservationRequest.java
  src/main/java/bdbe/bdbd/reservation/ReservationRestController.java
  src/main/java/bdbe/bdbd/reservation/ReservationService.java
  src/main/java/bdbe/bdbd/review/ReviewJPARepository.java
  src/main/java/bdbe/bdbd/review/ReviewResponse.java
  src/main/java/bdbe/bdbd/review/ReviewService.java
  src/main/java/bdbe/bdbd/user/OwnerRequest.java
  src/main/java/bdbe/bdbd/user/OwnerResponse.java
  src/main/java/bdbe/bdbd/user/OwnerRestController.java
  src/main/java/bdbe/bdbd/user/OwnerService.java
  src/main/java/bdbe/bdbd/user/UserService.java
  src/test/java/bdbe/bdbd/bay/BayRestControllerTest.java
  src/test/java/bdbe/bdbd/carwash/CarwashRestControllerTest.java
  src/test/java/bdbe/bdbd/file/FileRestControllerTest.java
  src/test/java/bdbe/bdbd/reservation/ReservationRestControllerTest.java
  src/test/java/bdbe/bdbd/review/ReviewRestControllerTest.java
  src/test/java/bdbe/bdbd/user/OwnerRestControllerTest.java
Labels: Request Review

#88 refactor: 파일 업로드 기능 리팩토링 및 세차장 등록에 반영
  src/main/java/bdbe/bdbd/_core/errors/GlobalExceptionHandler.java
  src/main/java/bdbe/bdbd/_core/errors/utils/FileUploadUtil.java
  src/main/java/bdbe/bdbd/carwash/CarwashRequest.java
  src/main/java/bdbe/bdbd/carwash/CarwashRestController.java
  src/main/java/bdbe/bdbd/carwash/CarwashService.java
  src/main/java/bdbe/bdbd/file/FileRequest.java
  src/main/java/bdbe/bdbd/file/FileResponse.java
  src/main/java/bdbe/bdbd/file/FileRestController.java
  src/main/java/bdbe/bdbd/file/FileService.java
  src/test/java/bdbe/bdbd/file/FileRestControllerTest.java
Labels: Type: Bug, Type: Enhancement, Priority: High, Status: Done

#89 config: dockerfile 설정
  .gitignore
  Dockerfile
  build.gradle
  src/main/java/bdbe/bdbd/_core/errors/utils/AWSConfig.java
Labels: Priority: High

#90 refactor: AwsConfig 위치 변경
  src/main/java/bdbe/bdbd/_core/errors/config/AWSConfig.java
Labels: Priority: Medium

#91 merge: from weekly to develop (배포 설정)
  .gitignore
  Dockerfile
  build.gradle
  src/main/java/bdbe/bdbd/_core/errors/GlobalExceptionHandler.java
  src/main/java/bdbe/bdbd/_core/errors/config/AWSConfig.java
  src/main/java/bdbe/bdbd/_core/errors/utils/FileUploadUtil.java
  src/main/java/bdbe/bdbd/carwash/CarwashRequest.java
  src/main/java/bdbe/bdbd/carwash/CarwashRestController.java
  src/main/java/bdbe/bdbd/carwash/CarwashService.java
  src/main/java/bdbe/bdbd/file/FileRequest.java
  src/main/java/bdbe/bdbd/file/FileResponse.java
  src/main/java/bdbe/bdbd/file/FileRestController.java
  src/main/java/bdbe/bdbd/file/FileService.java
  src/test/java/bdbe/bdbd/file/FileRestControllerTest.java
Labels: Priority: High

#92 merge: from develop to main (배포 설정)
  .gitignore
  Dockerfile
  build.gradle
  src/main/java/bdbe/bdbd/_core/errors/GlobalExceptionHandler.java
  src/main/java/bdbe/bdbd/_core/errors/config/AWSConfig.java
  src/main/java/bdbe/bdbd/_core/errors/utils/FileUploadUtil.java
  src/main/java/bdbe/bdbd/carwash/CarwashRequest.java
  src/main/java/bdbe/bdbd/carwash/CarwashRestController.java
  src/main/java/bdbe/bdbd/carwash/CarwashService.java
  src/main/java/bdbe/bdbd/file/FileRequest.java
  src/main/java/bdbe/bdbd/file/FileResponse.java
  src/main/java/bdbe/bdbd/file/FileRestController.java
  src/main/java/bdbe/bdbd/file/FileService.java
  src/test/java/bdbe/bdbd/file/FileRestControllerTest.java
Labels: Priority: High

#93 fix: dockerfile 수정
  Dockerfile
Labels: Priority: High

#94 fix: dockefile 수정
  Dockerfile
Labels: Priority: Urgent

#95 fix: dockerfile 수정
  Dockerfile
Labels: Priority: High

#96 feat: 이미지 업로드가 포함된 api 전체 반영
  src/main/java/bdbe/bdbd/carwash/CarwashResponse.java
  src/main/java/bdbe/bdbd/carwash/CarwashRestController.java
  src/main/java/bdbe/bdbd/carwash/CarwashService.java
  src/main/java/bdbe/bdbd/file/FileJPARepository.java
  src/main/java/bdbe/bdbd/reservation/ReservationResponse.java
  src/main/java/bdbe/bdbd/reservation/ReservationService.java
  src/main/java/bdbe/bdbd/user/OwnerResponse.java
  src/main/java/bdbe/bdbd/user/OwnerService.java
Labels: Type: Enhancement, Priority: High, Status: Done

#100 Add: yml 파일 추가
  .gitignore
  src/main/resources/application-dbtest.yml
  src/main/resources/application.yml
Labels: Priority: High

#101 merge: from weekly to develop
  .gitignore
  src/main/resources/application-dbtest.yml
  src/main/resources/application.yml
Labels: Priority: High

#102 merge: from deveop to main
  .gitignore
  src/main/resources/application-dbtest.yml
  src/main/resources/application.yml
Labels: Priority: High

#104 feat: k8s 추가
  k8s/backend.yaml
  k8s/configs/default.conf
  k8s/configs/init.sql
  k8s/frontend.yaml
  k8s/ingress.yaml
  k8s/kustomization.yaml
  k8s/mariadb.yaml
  k8s/nginx.yaml
Labels: Priority: High

#105 merge: from develop to main
  k8s/backend.yaml
  k8s/configs/default.conf
  k8s/configs/init.sql
  k8s/frontend.yaml
  k8s/ingress.yaml
  k8s/kustomization.yaml
  k8s/mariadb.yaml
  k8s/nginx.yaml
Labels: Priority: High

#106 fix: k8s 수정
  k8s/frontend.yaml
  k8s/kustomization.yaml
Labels: Priority: Urgent

#108 merge: from develop to main
  k8s/frontend.yaml
  k8s/kustomization.yaml
Labels: Priority: High

#110 fix: pull안되었을때 올린PR 충돌 해결
  src/main/java/bdbe/bdbd/carwash/CarwashResponse.java
  src/main/java/bdbe/bdbd/carwash/CarwashRestController.java
  src/main/java/bdbe/bdbd/carwash/CarwashService.java
  src/main/java/bdbe/bdbd/file/FileJPARepository.java
  src/main/java/bdbe/bdbd/user/OwnerResponse.java
  src/main/java/bdbe/bdbd/user/OwnerService.java
  src/main/resources/application-dbtest.yml
  src/test/java/bdbe/bdbd/carwash/CarwashRestControllerTest.java
Labels: Type: Enhancement, Priority: Medium, Status: Done

#112 merge: from weekly to develop
  .gitignore
  Dockerfile
  k8s/backend.yaml
  k8s/configs/default.conf
  k8s/configs/init.sql
  k8s/ingress.yaml
  k8s/kustomization.yaml
  k8s/mariadb.yaml
  k8s/nginx.yaml
  src/main/java/bdbe/bdbd/carwash/CarwashResponse.java
  src/main/java/bdbe/bdbd/carwash/CarwashRestController.java
  src/main/java/bdbe/bdbd/carwash/CarwashService.java
  src/main/java/bdbe/bdbd/file/FileJPARepository.java
  src/main/java/bdbe/bdbd/user/OwnerResponse.java
  src/main/java/bdbe/bdbd/user/OwnerService.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/test/java/bdbe/bdbd/carwash/CarwashRestControllerTest.java
Labels: Priority: High

#113 merge: from develop to main (배포설정)
  .gitignore
  Dockerfile
  k8s/backend.yaml
  k8s/configs/default.conf
  k8s/configs/init.sql
  k8s/ingress.yaml
  k8s/kustomization.yaml
  k8s/mariadb.yaml
  k8s/nginx.yaml
  src/main/java/bdbe/bdbd/carwash/CarwashResponse.java
  src/main/java/bdbe/bdbd/carwash/CarwashRestController.java
  src/main/java/bdbe/bdbd/carwash/CarwashService.java
  src/main/java/bdbe/bdbd/file/FileJPARepository.java
  src/main/java/bdbe/bdbd/user/OwnerResponse.java
  src/main/java/bdbe/bdbd/user/OwnerService.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/test/java/bdbe/bdbd/carwash/CarwashRestControllerTest.java
Labels: Priority: High

#114 refactor: member 엔티티로 변경
  README.md
  src/main/java/bdbe/bdbd/_core/errors/security/CustomUserDetails.java
  src/main/java/bdbe/bdbd/_core/errors/security/CustomUserDetailsService.java
  src/main/java/bdbe/bdbd/_core/errors/security/JWTProvider.java
  src/main/java/bdbe/bdbd/_core/errors/security/JwtAuthenticationFilter.java
  src/main/java/bdbe/bdbd/bay/BayResponse.java
  src/main/java/bdbe/bdbd/carwash/Carwash.java
  src/main/java/bdbe/bdbd/carwash/CarwashJPARepository.java
  src/main/java/bdbe/bdbd/carwash/CarwashRequest.java
  src/main/java/bdbe/bdbd/carwash/CarwashResponse.java
  src/main/java/bdbe/bdbd/carwash/CarwashRestController.java
  src/main/java/bdbe/bdbd/carwash/CarwashService.java
  src/main/java/bdbe/bdbd/member/Member.java
  src/main/java/bdbe/bdbd/member/MemberJPARepository.java
  src/main/java/bdbe/bdbd/member/MemberRequest.java
  src/main/java/bdbe/bdbd/member/MemberResponse.java
  src/main/java/bdbe/bdbd/member/MemberRestController.java
  src/main/java/bdbe/bdbd/member/MemberRole.java
  src/main/java/bdbe/bdbd/member/MemberService.java
  src/main/java/bdbe/bdbd/member/OwnerRequest.java
  src/main/java/bdbe/bdbd/member/OwnerResponse.java
  src/main/java/bdbe/bdbd/member/OwnerRestController.java
  src/main/java/bdbe/bdbd/member/OwnerService.java
  src/main/java/bdbe/bdbd/optime/OptimeJPARepository.java
  src/main/java/bdbe/bdbd/reservation/Reservation.java
  src/main/java/bdbe/bdbd/reservation/ReservationJPARepository.java
  src/main/java/bdbe/bdbd/reservation/ReservationRequest.java
  src/main/java/bdbe/bdbd/reservation/ReservationRestController.java
  src/main/java/bdbe/bdbd/reservation/ReservationService.java
  src/main/java/bdbe/bdbd/review/Review.java
  src/main/java/bdbe/bdbd/review/ReviewJPARepository.java
  src/main/java/bdbe/bdbd/review/ReviewRequest.java
  src/main/java/bdbe/bdbd/review/ReviewResponse.java
  src/main/java/bdbe/bdbd/review/ReviewRestController.java
  src/main/java/bdbe/bdbd/review/ReviewService.java
  src/main/java/bdbe/bdbd/user/OwnerRequest.java
  src/main/java/bdbe/bdbd/user/UserJPARepository.java
  src/main/java/bdbe/bdbd/user/UserRole.java
  src/main/resources/application-dbtest.yml
  src/test/java/bdbe/bdbd/carwash/CarwashRestControllerTest.java
  src/test/java/bdbe/bdbd/member/MemberRestControllerTest.java
  src/test/java/bdbe/bdbd/member/OwnerRestControllerTest.java
  src/test/java/bdbe/bdbd/reservation/ReservationRestControllerTest.java
  src/test/java/bdbe/bdbd/review/ReviewRestControllerTest.java
Labels: Type: Enhancement, Priority: High, Status: Done

#115 Revert "refactor: member 엔티티로 변경"
  README.md
  src/main/java/bdbe/bdbd/_core/errors/security/CustomUserDetails.java
  src/main/java/bdbe/bdbd/_core/errors/security/CustomUserDetailsService.java
  src/main/java/bdbe/bdbd/_core/errors/security/JWTProvider.java
  src/main/java/bdbe/bdbd/_core/errors/security/JwtAuthenticationFilter.java
  src/main/java/bdbe/bdbd/bay/BayResponse.java
  src/main/java/bdbe/bdbd/carwash/Carwash.java
  src/main/java/bdbe/bdbd/carwash/CarwashJPARepository.java
  src/main/java/bdbe/bdbd/carwash/CarwashRequest.java
  src/main/java/bdbe/bdbd/carwash/CarwashResponse.java
  src/main/java/bdbe/bdbd/carwash/CarwashRestController.java
  src/main/java/bdbe/bdbd/carwash/CarwashService.java
  src/main/java/bdbe/bdbd/member/MemberJPARepository.java
  src/main/java/bdbe/bdbd/member/MemberRole.java
  src/main/java/bdbe/bdbd/member/OwnerRequest.java
  src/main/java/bdbe/bdbd/optime/OptimeJPARepository.java
  src/main/java/bdbe/bdbd/reservation/Reservation.java
  src/main/java/bdbe/bdbd/reservation/ReservationJPARepository.java
  src/main/java/bdbe/bdbd/reservation/ReservationRequest.java
  src/main/java/bdbe/bdbd/reservation/ReservationRestController.java
  src/main/java/bdbe/bdbd/reservation/ReservationService.java
  src/main/java/bdbe/bdbd/review/Review.java
  src/main/java/bdbe/bdbd/review/ReviewJPARepository.java
  src/main/java/bdbe/bdbd/review/ReviewRequest.java
  src/main/java/bdbe/bdbd/review/ReviewResponse.java
  src/main/java/bdbe/bdbd/review/ReviewRestController.java
  src/main/java/bdbe/bdbd/review/ReviewService.java
  src/main/java/bdbe/bdbd/user/OwnerRequest.java
  src/main/java/bdbe/bdbd/user/OwnerResponse.java
  src/main/java/bdbe/bdbd/user/OwnerRestController.java
  src/main/java/bdbe/bdbd/user/OwnerService.java
  src/main/java/bdbe/bdbd/user/User.java
  src/main/java/bdbe/bdbd/user/UserJPARepository.java
  src/main/java/bdbe/bdbd/user/UserRequest.java
  src/main/java/bdbe/bdbd/user/UserResponse.java
  src/main/java/bdbe/bdbd/user/UserRestController.java
  src/main/java/bdbe/bdbd/user/UserRole.java
  src/main/java/bdbe/bdbd/user/UserService.java
  src/main/resources/application-dbtest.yml
  src/test/java/bdbe/bdbd/carwash/CarwashRestControllerTest.java
  src/test/java/bdbe/bdbd/reservation/ReservationRestControllerTest.java
  src/test/java/bdbe/bdbd/review/ReviewRestControllerTest.java
  src/test/java/bdbe/bdbd/user/OwnerRestControllerTest.java
  src/test/java/bdbe/bdbd/user/UserRestControllerTest.java
Labels: Priority: High

#116 delete: src/main/resources/application-dbtest.yml
  src/main/resources/application-dbtest.yml
Labels: Priority: High

#120 refactor: api 경로에 /api 추가
  src/main/java/bdbe/bdbd/bay/BayRestController.java
  src/main/java/bdbe/bdbd/carwash/CarwashRestController.java
  src/main/java/bdbe/bdbd/member/MemberRestController.java
  src/main/java/bdbe/bdbd/member/OwnerRestController.java
  src/main/java/bdbe/bdbd/reservation/ReservationRestController.java
  src/main/java/bdbe/bdbd/review/ReviewRestController.java
  src/test/java/bdbe/bdbd/bay/BayRestControllerTest.java
  src/test/java/bdbe/bdbd/carwash/CarwashRestControllerTest.java
  src/test/java/bdbe/bdbd/member/MemberRestControllerTest.java
  src/test/java/bdbe/bdbd/member/OwnerRestControllerTest.java
  src/test/java/bdbe/bdbd/reservation/ReservationRestControllerTest.java
  src/test/java/bdbe/bdbd/review/ReviewRestControllerTest.java
Labels: Priority: High

#121 Revert "refactor: api 경로에 /api 추가"
  src/main/java/bdbe/bdbd/bay/BayRestController.java
  src/main/java/bdbe/bdbd/carwash/CarwashRestController.java
  src/main/java/bdbe/bdbd/member/MemberRestController.java
  src/main/java/bdbe/bdbd/member/OwnerRestController.java
  src/main/java/bdbe/bdbd/reservation/ReservationRestController.java
  src/main/java/bdbe/bdbd/review/ReviewRestController.java
  src/test/java/bdbe/bdbd/bay/BayRestControllerTest.java
  src/test/java/bdbe/bdbd/carwash/CarwashRestControllerTest.java
  src/test/java/bdbe/bdbd/member/MemberRestControllerTest.java
  src/test/java/bdbe/bdbd/member/OwnerRestControllerTest.java
  src/test/java/bdbe/bdbd/reservation/ReservationRestControllerTest.java
  src/test/java/bdbe/bdbd/review/ReviewRestControllerTest.java
Labels: Priority: Urgent

#122 fix: api에 /api/ 추가
  src/main/java/bdbe/bdbd/bay/BayRestController.java
  src/main/java/bdbe/bdbd/carwash/CarwashRestController.java
  src/main/java/bdbe/bdbd/member/MemberRestController.java
  src/main/java/bdbe/bdbd/member/OwnerRestController.java
  src/main/java/bdbe/bdbd/reservation/ReservationRestController.java
  src/main/java/bdbe/bdbd/review/ReviewRestController.java
  src/test/java/bdbe/bdbd/bay/BayRestControllerTest.java
  src/test/java/bdbe/bdbd/carwash/CarwashRestControllerTest.java
  src/test/java/bdbe/bdbd/member/MemberRestControllerTest.java
  src/test/java/bdbe/bdbd/member/OwnerRestControllerTest.java
  src/test/java/bdbe/bdbd/reservation/ReservationRestControllerTest.java
  src/test/java/bdbe/bdbd/review/ReviewRestControllerTest.java
Labels: Priority: High

#124 delete: src/main/resources/application-dbtest.yml
  src/main/resources/application-dbtest.yml
Labels: Priority: High

#125 merge: from develop to main
  README.md
  src/main/java/bdbe/bdbd/_core/errors/security/CustomUserDetails.java
  src/main/java/bdbe/bdbd/_core/errors/security/CustomUserDetailsService.java
  src/main/java/bdbe/bdbd/_core/errors/security/JWTProvider.java
  src/main/java/bdbe/bdbd/_core/errors/security/JwtAuthenticationFilter.java
  src/main/java/bdbe/bdbd/bay/BayResponse.java
  src/main/java/bdbe/bdbd/bay/BayRestController.java
  src/main/java/bdbe/bdbd/carwash/Carwash.java
  src/main/java/bdbe/bdbd/carwash/CarwashJPARepository.java
  src/main/java/bdbe/bdbd/carwash/CarwashRequest.java
  src/main/java/bdbe/bdbd/carwash/CarwashResponse.java
  src/main/java/bdbe/bdbd/carwash/CarwashRestController.java
  src/main/java/bdbe/bdbd/carwash/CarwashService.java
  src/main/java/bdbe/bdbd/member/Member.java
  src/main/java/bdbe/bdbd/member/MemberJPARepository.java
  src/main/java/bdbe/bdbd/member/MemberRequest.java
  src/main/java/bdbe/bdbd/member/MemberResponse.java
  src/main/java/bdbe/bdbd/member/MemberRestController.java
  src/main/java/bdbe/bdbd/member/MemberRole.java
  src/main/java/bdbe/bdbd/member/MemberService.java
  src/main/java/bdbe/bdbd/member/OwnerRequest.java
  src/main/java/bdbe/bdbd/member/OwnerResponse.java
  src/main/java/bdbe/bdbd/member/OwnerRestController.java
  src/main/java/bdbe/bdbd/member/OwnerService.java
  src/main/java/bdbe/bdbd/optime/OptimeJPARepository.java
  src/main/java/bdbe/bdbd/reservation/Reservation.java
  src/main/java/bdbe/bdbd/reservation/ReservationJPARepository.java
  src/main/java/bdbe/bdbd/reservation/ReservationRequest.java
  src/main/java/bdbe/bdbd/reservation/ReservationRestController.java
  src/main/java/bdbe/bdbd/reservation/ReservationService.java
  src/main/java/bdbe/bdbd/review/Review.java
  src/main/java/bdbe/bdbd/review/ReviewJPARepository.java
  src/main/java/bdbe/bdbd/review/ReviewRequest.java
  src/main/java/bdbe/bdbd/review/ReviewResponse.java
  src/main/java/bdbe/bdbd/review/ReviewRestController.java
  src/main/java/bdbe/bdbd/review/ReviewService.java
  src/main/java/bdbe/bdbd/user/OwnerRequest.java
  src/main/java/bdbe/bdbd/user/UserJPARepository.java
  src/main/java/bdbe/bdbd/user/UserRole.java
  src/main/resources/application-dbtest.yml
  src/test/java/bdbe/bdbd/bay/BayRestControllerTest.java
  src/test/java/bdbe/bdbd/carwash/CarwashRestControllerTest.java
  src/test/java/bdbe/bdbd/member/MemberRestControllerTest.java
  src/test/java/bdbe/bdbd/member/OwnerRestControllerTest.java
  src/test/java/bdbe/bdbd/reservation/ReservationRestControllerTest.java
  src/test/java/bdbe/bdbd/review/ReviewRestControllerTest.java
Labels: Priority: High
